### ISSUE TITLE
🐞 Panic when extracting action

### ISSUE THREAD

**Issue by nicolaiunrein** [dagger/dagger#2279]
### What is the issue?

Seems that dagger is crashing on dereferencing Secrets in certain cases.
Consider the below code example and stack trace.

It's my first day with dagger and I like it a lot so far ❤️ 

```bash
# running the below action with:
> SSH_KEY_STRING="" SSH_KEY_SECRET="" dagger do fail -l debug --log-format plain   
```
...produces this error:

### Log output
```
panic: not properly initialized (state: unprocessed, value: <nil>)

goroutine 113 [running]:
cuelang.org/go/cue.makeValue(0xc0002c7db0, 0xc0019c1200, 0x0, 0xc001311e60, 0x3, 0x3)
        /home/runner/go/pkg/mod/github.com/dagger/cue@v0.4.1-rc.1.0.20220121023213-66df011a52c2/cue/types.go:668 +0x137
cuelang.org/go/cue.Value.LookupPath(0xc0002c7db0, 0xc0019c0f30, 0x0, 0xc000354de0, 0x3, 0x3, 0xc0007b8000, 0x0, 0xc000775588)
        /home/runner/go/pkg/mod/github.com/dagger/cue@v0.4.1-rc.1.0.20220121023213-66df011a52c2/cue/query.go:77 +0x47c
go.dagger.io/dagger/compiler.(*Value).LookupPath(0xc001a5d020, 0xc000354de0, 0x3, 0x3, 0x0)
        /home/runner/work/dagger/dagger/compiler/value.go:62 +0xc7
go.dagger.io/dagger/plancontext.IsSecretValue(0xc001a5d020, 0xc)
        /home/runner/work/dagger/dagger/plancontext/secret.go:21 +0x53
go.dagger.io/dagger/plan/task.(*execTask).getRunOpts(0x2b5f800, 0xc001a5c740, 0xc0005b08d0, 0xc001426d70, 0x1ea7ec0, 0xc0015a6bb0, 0xc0014b4f00, 0x0)
        /home/runner/work/dagger/dagger/plan/task/exec.go:82 +0x338
go.dagger.io/dagger/plan/task.(*execTask).Run(0x2b5f800, 0x2310ea0, 0xc0013114a0, 0xc0005b08d0, 0xc0010046c0, 0xc001a5c740, 0x0, 0x0, 0x2310ea0)
        /home/runner/work/dagger/dagger/plan/task/exec.go:35 +0x14a
go.dagger.io/dagger/plan.(*Runner).taskFunc.func1(0xc000e7d5e0, 0x0, 0x0)
        /home/runner/work/dagger/dagger/plan/runner.go:174 +0x708
cuelang.org/go/tools/flow.RunnerFunc.Run(0xc00178ed60, 0xc000e7d5e0, 0x0, 0x0, 0x18f39e0, 0xc0019c02d0)
        /home/runner/go/pkg/mod/github.com/dagger/cue@v0.4.1-rc.1.0.20220121023213-66df011a52c2/tools/flow/flow.go:114 +0x30
cuelang.org/go/tools/flow.(*Controller).runLoop.func1(0xc000e7d5e0)
        /home/runner/go/pkg/mod/github.com/dagger/cue@v0.4.1-rc.1.0.20220121023213-66df011a52c2/tools/flow/run.go:67 +0x48
created by cuelang.org/go/tools/flow.(*Controller).runLoop
        /home/runner/go/pkg/mod/github.com/dagger/cue@v0.4.1-rc.1.0.20220121023213-66df011a52c2/tools/flow/run.go:66 +0x1bb
```

#### Minimal Reproducable Example
```cue
package testcase

import (
    "dagger.io/dagger"
    "dagger.io/dagger/core"
    "universe.dagger.io/bash"
    "universe.dagger.io/docker"
)

dagger.#Plan & {
    client: env: {
        SSH_KEY_SECRET: dagger.#Secret
        SSH_KEY_STRING: string
    }

    actions: {
         // Will fail when run
        fail: docker.#Build & {
            steps: [
                docker.#Pull & {
                    source: "index.docker.io/rust:1.60.0"
                },

                #Fail & {
                    sshKey: client.env.SSH_KEY_SECRET
                },
            ]
        }


        // It works inlined
        ok: docker.#Build & {
            steps: [
                docker.#Pull & {
                    source: "index.docker.io/rust:1.60.0"
                },

                bash.#Run & {
                    env: {
                        "SSH_KEY_SECRET": client.env.SSH_KEY_STRING
                    }

                    script: contents: "echo hello"
                    always: true
                }
            ]
        }


        // It also works whe I replace the Secret with a string
        okToo: docker.#Build & {
            steps: [
                docker.#Pull & {
                    source: "index.docker.io/rust:1.60.0"
                },

                #Ok & {
                    sshKey: client.env.SSH_KEY_STRING
                },
            ]
        }

    }
}

#Fail: {
    sshKey: core.#Secret

    bash.#Run & {
        env: {
            "sshKey": sshKey
        }

        script: contents: "echo hello"
        always: true
    }
}

#Ok: {
    sshKey: string

    bash.#Run & {
        env: {
            "sshKey": sshKey
        }

        script: contents: "echo hello"
        always: true
    }
}


```

### Dagger version

dagger 0.2.7 (18c19174) darwin/amd64

### OS version

macOS 10.14.6

**Comment by aluzzardi** [comment]
Thanks for the bug report, @nicolaiunrein!

Figured out the issue, it's a small issue in the config (it's `dagger.#Secret`, not `core.#Secret`):

```diff
5d4
<       "dagger.io/dagger/core"
65c64
<       sshKey: core.#Secret
---
>       sshKey: dagger.#Secret
```

However, the strange thing is that it's causing CUE to panic somehow. Need to figure out the root cause. I think this is related to #1572 -- when pointing to non existing fields (e.g. `core.#DoesNotExist`), CUE acts in a strange way.

/cc @jlongtine @dolanor @helderco

**Comment by nicolaiunrein** [comment]
Ooops! Thanks for the reply! I will give it a try later!
