### ISSUE TITLE
🐞 `dagger do --help` panics

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#2596]
## Problem

When running `dagger do --help` on a valid plan, I see the following error:

```
$ dagger do --help
panic: event: Action cannot be empty

goroutine 1 [running]:
go.dagger.io/dagger/telemetry.(*Telemetry).Push(0xc00046ae70, {0x3?, 0xc003e3f9b8?}, {0x1493fd8?, 0xc002940b80?})
        /src/telemetry/telemetry.go:88 +0x11e
go.dagger.io/dagger/cmd/dagger/cmd.glob..func2(0x1cabcc0, {0xc000122200, 0x1, 0x1})
        /src/cmd/dagger/cmd/do.go:91 +0x70c
github.com/spf13/cobra.(*Command).execute(0x1cabcc0, {0xc000122200, 0x1, 0x1})
        /root/.cache/go-mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x1cac6c0)
        /root/.cache/go-mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /root/.cache/go-mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /root/.cache/go-mod/github.com/spf13/cobra@v1.4.0/command.go:895
go.dagger.io/dagger/cmd/dagger/cmd.Execute()
        /src/cmd/dagger/cmd/root.go:96 +0x478
main.main()
        /src/cmd/dagger/main.go:8 +0x17
```

When executing an action in the same plan, for example `dagger do build`, the action is executed normally with no issue.

## Dagger version

Devel, git commit `eaff2c63d3fd41d85bb6fc6eed4cb515613b7a18`.

**Comment by gerhard** [comment]
Great spot & fix @shykes, thank you! 🙌

Good decision @marcosnils for sitting on this an extra day. We should be good to cut another patch release today. Shout out @aluzzardi if you think otherwise.

All looks good on our end @slumbering & @mircubed.
