### ISSUE TITLE
🐞 Panic when validating plan on secret types that unify with a decoded secret value

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#2789]
### What is the issue?

When you pass a decoded secret to a `dagger.#Secret` field, the validator panics.

Essentially this:

```cue
token: dagger.#Secret & decode.output.apiToken.contents
```

When checking for core types, we need to do it only if it's a struct:

```go
	// Core types (FS, Secret, Socket): make sure they are references, otherwise abort.
	case plancontext.IsFSValue(v) || plancontext.IsSecretValue(v) || plancontext.IsSocketValue(v):
```

As a workaround for now there's ways to avoid this situation, but no immediate general recommendation.

### Log output

```console
panic: not properly initialized (state: unprocessed, value: <nil>)

goroutine 1 [running]:
cuelang.org/go/cue.makeValue(0x10197b2d8?, 0x101970948?, 0x14000ed9560?)
        /Users/helder/go/pkg/mod/github.com/dagger/cue@v0.4.1-rc.1.0.20220121023213-66df011a52c2/cue/types.go:668 +0xc8
cuelang.org/go/cue.Value.LookupPath({0x140003c3d50?, 0x14000ed94d0?, 0x0?}, {{0x140003eb830?, 0x14000680000?, 0x140011ee160?}})
        /Users/helder/go/pkg/mod/github.com/dagger/cue@v0.4.1-rc.1.0.20220121023213-66df011a52c2/cue/query.go:77 +0x4a0
go.dagger.io/dagger/compiler.(*Value).LookupPath(0x140011ee140, {{0x140003eb830?, 0x14000ed94d0?, 0x140003c3d50?}})
        /Users/helder/Projects/dagger/compiler/value.go:63 +0xf4
go.dagger.io/dagger/plancontext.IsFSValue(0x140011ee140?)
        /Users/helder/Projects/dagger/plancontext/fs.go:22 +0x3c
go.dagger.io/dagger/plan.isPlanConcrete(0x14000001611?, 0x140011ee140)
        /Users/helder/Projects/dagger/plan/validate.go:76 +0xd4
go.dagger.io/dagger/plan.isPlanConcrete(0x14000000681?, 0x14001201f80)
        /Users/helder/Projects/dagger/plan/validate.go:113 +0x400
go.dagger.io/dagger/plan.isPlanConcrete(0x14000001634?, 0x140010f03a0)
        /Users/helder/Projects/dagger/plan/validate.go:113 +0x400
go.dagger.io/dagger/plan.isPlanConcrete(0x14000001651?, 0x140010f0180)
        /Users/helder/Projects/dagger/plan/validate.go:113 +0x400
go.dagger.io/dagger/plan.isPlanConcrete(0x140000006d1?, 0x1400083ffe0)
        /Users/helder/Projects/dagger/plan/validate.go:113 +0x400
go.dagger.io/dagger/plan.isPlanConcrete(0x14000aff280?, 0x1400083f400)
        /Users/helder/Projects/dagger/plan/validate.go:113 +0x400
go.dagger.io/dagger/plan.(*Plan).validate(0x14001188540, {0x101979228, 0x14000b33a40})
        /Users/helder/Projects/dagger/plan/plan.go:272 +0xc0
go.dagger.io/dagger/plan.Load({0x101979228, 0x14000b339e0}, {{0x14000b75420, 0x1, 0x1}, {0x1023d4e38, 0x0, 0x0}, {0x0, 0x0}, ...})
        /Users/helder/Projects/dagger/plan/plan.go:91 +0x5d4
go.dagger.io/dagger/cmd/dagger/cmd.loadPlan({0x101979228, 0x14000b339e0}, {0x16fa1f73d, 0x16})
        /Users/helder/Projects/dagger/cmd/dagger/cmd/do.go:281 +0x13c
go.dagger.io/dagger/cmd/dagger/cmd.glob..func2(0x10236f3c0, {0x14000aff3c0, 0x3, 0x4})
        /Users/helder/Projects/dagger/cmd/dagger/cmd/do.go:83 +0x2a8
github.com/spf13/cobra.(*Command).execute(0x10236f3c0, {0x14000aff3c0, 0x3, 0x4})
        /Users/helder/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x4b8
github.com/spf13/cobra.(*Command).ExecuteC(0x10236fdc0)
        /Users/helder/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/helder/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /Users/helder/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:911
go.dagger.io/dagger/cmd/dagger/cmd.Execute()
        /Users/helder/Projects/dagger/cmd/dagger/cmd/root.go:96 +0x398
main.main()
        /Users/helder/Projects/dagger/cmd/dagger/main.go:8 +0x20
exit status 2
```

### Steps to reproduce

```cue
package main

import (
	"encoding/yaml"
	"dagger.io/dagger"
	"dagger.io/dagger/core"
	"universe.dagger.io/bash"
)

dagger.#Plan & {
	actions: {
		write: core.#WriteFile & {
			input:    dagger.#Scratch
			path:     "/secret"
			contents: yaml.Marshal({
				apiToken: "foobar"
			})
		}

		secret: core.#NewSecret & {
			input: write.output
			path:  "/secret"
		}

		decode: core.#DecodeSecret & {
			input:  secret.output
			format: "yaml"
		}

		test: #Run & {
			token: decode.output.apiToken.contents
		}
	}
}

#Run: {
	token: dagger.#Secret

	_run: bash.#RunSimple & {
		env: TOKEN:       token
		script: contents: "echo -n $TOKEN > /out"
		export: files: "/out": _
		always: true
	}

	verify: _run.export.files."/out"
}
```

### Dagger version

dagger devel (31b0522df) darwin/arm64

### OS version

macOS 12.4

/cc @marcosnils @rawkode

**Comment by helderco** [comment]
Just a quick update. The panic itself is easy enough to fix, the more complicated part is detecting `core.#DecodeSecret` references to skip validation. They have a recursive output type that don't allow for correct validation during load:

```cue
actions: test: token: dagger.#Secret & decode.output.apiToken.contents

// failed to load plan: actions.test.token: undefined field: apiToken:
```

**Comment by helderco** [comment]
Focused on the Python SDK now. @jlongtine, can you triage this?

**Comment by TomChv** [comment]
This issue is outdated and relates to our CUE version. 
I'm closing it now since we will not work on that
