### ISSUE TITLE
✨ Support gradle test with testcontainers

### ISSUE THREAD

**Issue by pipinet** [dagger/dagger#2972]
### What are you trying to do?

1:32AM INFO  actions.check.run._exec | #9 492.3 Can not connect to Ryuk at localhost:65170
1:32AM INFO  actions.check.run._exec | #9 492.3 java.net.ConnectException: Connection refused
1:32AM INFO  actions.check.run._exec | #9 492.3 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
1:32AM INFO  actions.check.run._exec | #9 492.3 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
1:32AM INFO  actions.check.run._exec | #9 492.3 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
1:32AM INFO  actions.check.run._exec | #9 492.3 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
1:32AM INFO  actions.check.run._exec | #9 492.3 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
1:32AM INFO  actions.check.run._exec | #9 492.3 	at java.base/java.net.Socket.connect(Socket.java:633)
1:32AM INFO  actions.check.run._exec | #9 492.3 	at org.testcontainers.utility.RyukResourceReaper.lambda$null$0(RyukResourceReaper.java:92)
1:32AM INFO  actions.check.run._exec | #9 492.3 	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
1:32AM INFO  actions.check.run._exec | #9 492.3 	at org.testcontainers.utility.RyukResourceReaper.lambda$maybeStart$1(RyukResourceReaper.java:88)
1:32AM INFO  actions.check.run._exec | #9 492.3 	at java.base/java.lang.Thread.run(Thread.java:833)
1:32AM INFO  actions.check.run._exec | #9 492.3 Can not connect to Ryuk at localhost:65169
1:32AM INFO  actions.check.run._exec | #9 492.3 java.net.ConnectException: Connection refused
1:32AM INFO  actions.check.run._exec | #9 492.3 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
1:32AM INFO  actions.check.run._exec | #9 492.3 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
1:32AM INFO  actions.check.run._exec | #9 492.3 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
1:32AM INFO  actions.check.run._exec | #9 492.3 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
1:32AM INFO  actions.check.run._exec | #9 492.3 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
1:32AM INFO  actions.check.run._exec | #9 492.3 	at java.base/java.net.Socket.connect(Socket.java:633)
1:32AM INFO  actions.check.run._exec | #9 492.3 	at org.testcontainers.utility.RyukResourceReaper.lambda$null$0(RyukResourceReaper.java:92)
1:32AM INFO  actions.check.run._exec | #9 492.3 	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
1:32AM INFO  actions.check.run._exec | #9 492.3 	at org.testcontainers.utility.RyukResourceReaper.lambda$maybeStart$1(RyukResourceReaper.java:88)
1:32AM INFO  actions.check.run._exec | #9 492.3 	at java.base/java.lang.Thread.run(Thread.java:833)
1:32AM DEBUG actions.check.run._exec | #9 CANCELED
1:32AM FATAL system | failed to execute plan: failed to run Build function: context canceled

**Comment by slumbering** [comment]
No enough context to this issue. Closing now but feel free to reopen
