### ISSUE TITLE
🐞 Node.js SDK - ClientError: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by slumbering** [dagger/dagger#4130]
### What is the issue?

I'm trying to write a new file with the following script:

KO
```typescript
import Client, { connect } from "@dagger.io/dagger"

connect(async (client: Client) => {
    const newFile = await client
       .container()
       .directory("/").entries()
})
```

OK
```typescript
import Client, { connect } from "@dagger.io/dagger"

connect(async (client: Client) => {
    const newFile = await client
       .container()
       .from("alpine")
       .directory("/").entries()
})
```

### Log output

```bash
(node:41070) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///private/tmp/my-app/node_modules/@dagger.io/dagger/dist/api/utils.js:5
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
                                                                ^
GraphQLRequestError: Error message
    at file:///private/tmp/my-app/node_modules/@dagger.io/dagger/dist/api/utils.js:119:23
    at Generator.throw (<anonymous>)
    at rejected (file:///private/tmp/my-app/node_modules/@dagger.io/dagger/dist/api/utils.js:5:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  cause: ClientError: runtime error: invalid memory address or nil pointer dereference: {"response":{"data":null,"errors":[{"message":"r
untime error: invalid memory address or nil pointer dereference","locations":[{"line":5,"column":9}],"path":["container","directory"]}],"status":200,"headers":{}},"request":{"query":"\n        {\n        container  {\n      \n        directory (path: \"/\") {\n      \n        withNewFile (path: \"myfile\",contents: \"This string has quotes \\\"\") {\n      \n        file (path: \"myfile\") {\n      \n        id  }}}}\n      }\n      "}}                                                                                                              at /private/tmp/my-app/node_modules/graphql-request/src/index.ts:497:11
      at step (/private/tmp/my-app/node_modules/graphql-request/dist/index.js:63:23)
      at Object.next (/private/tmp/my-app/node_modules/graphql-request/dist/index.js:44:53)
      at fulfilled (/private/tmp/my-app/node_modules/graphql-request/dist/index.js:35:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    response: { data: null, errors: [Array], status: 200, headers: [Headers] },
    request: {
      query: '\n' +
        '        {\n' +
        '        container  {\n' +
        '      \n' +
        '        directory (path: "/") {\n' +
        '      \n' +
        '        withNewFile (path: "myfile",contents: "This string has quotes \\"") {\n' +
        '      \n' +
        '        file (path: "myfile") {\n' +
        '      \n' +
        '        id  }}}}\n' +
        '      }\n' +
        '      ',
      variables: undefined
    }
  },
  code: 'D100',
  requestContext: {
    query: '\n' +
      '        {\n' +
      '        container  {\n' +
      '      \n' +
      '        directory (path: "/") {\n' +
      '      \n' +
      '        withNewFile (path: "myfile",contents: "This string has quotes \\"") {\n' +
      '      \n' +
      '        file (path: "myfile") {\n' +
      '      \n' +
      '        id  }}}}\n' +
      '      }\n' +
      '      ',
    variables: undefined
  },
  response: {
    data: null,
    errors: [ [Object] ],
    status: 200,
    headers: Headers { [Symbol(map)]: [Object: null prototype] }
  }
}
```

### Steps to reproduce

1 - Follow the getting started steps 1 and 2 to install Dagger SDK:
- https://docs.dagger.io/sdk/nodejs/783645/get-started#step-1-create-a-react-application
- https://docs.dagger.io/sdk/nodejs/783645/get-started#step-2-install-the-dagger-nodejs-sdk

2 - Create a new file `.ts` (eg: `build.ts`) in your root dir

3 - Copy paste the following script:
```ts
import Client, { connect } from "@dagger.io/dagger"

connect(async (client: Client) => {

  const stringWithQuotes = "This string has quotes \""
  const newFile = await client
       .container()
       .directory("/")
       .withNewFile("myfile", stringWithQuotes)
       .file("myfile").id()
})
```

4 - Run this command (if necessary change `build.ts` with your script name): 
```bash
node --loader ts-node/esm ./build.ts
```

### Dagger version

dagger devel (c3124a930) darwin/arm64

### OS version

macOs 13.0.1 (22A400)

**Comment by slumbering** [comment]
cc @aluzzardi @sipsma

**Comment by slumbering** [comment]
Did you get the chance to tackle this issue @sipsma @aluzzardi ? Or maybe I'm doing something wrong in the example above ? Thanks

**Comment by slumbering** [comment]
👋 @sipsma @aluzzardi . Adding `.from('alpine')` removes the error.

**Comment by slumbering** [comment]
Same error with go:

```shell
Building with Dagger
[]
input:1: container.directory runtime error: invalid memory address or nil pointer dereference

Please visit https://dagger.io/help#go for troubleshooting guidance.
```

**Comment by aluzzardi** [comment]
Looks like a bug deep down, not converting a nil pointer into an llb.Scratch

@vito Would you know if there's one magic spot where we could handle that?

**Comment by vito** [comment]
Closing optimistically as https://github.com/dagger/dagger/pull/4248#discussion_r1067288276 included a fix for this
