### ISSUE TITLE
🐞 NodeJS error types are not exported

### ISSUE THREAD

**Issue by dolanor** [dagger/dagger#4150]
### What is the issue?

I want to use the new errors from the NodeJS SDK v0.3.0, but I don't know how to access it.
It seems they are not exported from the SDK `index.ts`.

### Log output

```
/home/dolanor/src/demos/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
build.ts:2:43 - error TS2307: Cannot find module '@dagger.io/dagger/common/errors' or its corresponding type declarations.

2 import {EngineSessionPortParseError} from "@dagger.io/dagger/common/errors"
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/home/dolanor/src/demos/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/dolanor/src/demos/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/dolanor/src/demos/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/home/dolanor/src/demos/node_modules/ts-node/src/index.ts:1433:41)
    at transformSource (/home/dolanor/src/demos/node_modules/ts-node/src/esm.ts:400:37)
    at /home/dolanor/src/demos/node_modules/ts-node/src/esm.ts:278:53
    at async addShortCircuitFlag (/home/dolanor/src/demos/node_modules/ts-node/src/esm.ts:409:15)
    at async nextLoad (node:internal/modules/esm/loader:161:22)
    at async ESMLoader.load (node:internal/modules/esm/loader:593:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:445:11) {
  diagnosticCodes: [ 2307 ]
}

```

or

```
home/dolanor/src/demos/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
build.ts:2:9 - error TS2614: Module '"@dagger.io/dagger"' has no exported member 'EngineSessionPortParseError'. Did you mean to use 'import EngineSessionPortParseError from "@dagger.io/dagger"' instead?

2 import {EngineSessionPortParseError} from "@dagger.io/dagger"
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/home/dolanor/src/demos/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/dolanor/src/demos/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/dolanor/src/demos/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/home/dolanor/src/demos/node_modules/ts-node/src/index.ts:1433:41)
    at transformSource (/home/dolanor/src/demos/node_modules/ts-node/src/esm.ts:400:37)
    at /home/dolanor/src/demos/node_modules/ts-node/src/esm.ts:278:53
    at async addShortCircuitFlag (/home/dolanor/src/demos/node_modules/ts-node/src/esm.ts:409:15)
    at async nextLoad (node:internal/modules/esm/loader:161:22)
    at async ESMLoader.load (node:internal/modules/esm/loader:593:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:445:11) {
  diagnosticCodes: [ 2614 ]
}
```

### Steps to reproduce

```typescript
import EngineSessionPortParseError from "@dagger.io/dagger"
```

or

```typescript
import EngineSessionPortParseError from "@dagger.io/dagger/common/errors"
```

### Dagger version

Dagger NodeJS SDK v0.3.0

### OS version

Ubuntu 20.04

**Comment by TomChv** [comment]
Is it fixed by https://github.com/dagger/dagger/pull/4227 ?

**Comment by dolanor** [comment]
I thought so, but after testing, it's not the case. I need to create a use case for @slumbering so he can think on what to do.

**Comment by TomChv** [comment]
@dolanor I can't reproduce the error with the following test using the setup explained in our [dev doc](https://github.com/dagger/dagger/tree/main/sdk/nodejs#local-development). Can you give me more context about your error? A repro case would be perfect.

```ts
import EngineSessionPortParseError from "@dagger.io/dagger"

function main() {
  console.log("Hello world")

  throw new EngineSessionPortParseError()
}


try {
  main();
} catch (e) {
  console.log(e)
}
```

Result:

```
yarn run v1.22.19
$ node index.js
Hello world
Client {
  _queryTree: [],
  clientHost: '127.0.0.1:8080',
  sessionToken: '',
  client: GraphQLClient {
    url: 'http://undefined/query',
    options: { headers: [Object] }
  }
}
```

**Comment by dolanor** [comment]
```js
// this creates an alias of @dagger.io/dagger.Client named as EngineSessionPortParseError
// import EngineSessionPortParseError from "@dagger.io/dagger"

// this explicitely import exported types who have that name
import { EngineSessionPortParseError } from "@dagger.io/dagger"

function main() {
  console.log("Hello world")

  // in your code, you were just returning a default initialized Client, it is not the error you expected
  throw new EngineSessionPortParseError()
}


try {
  main();
} catch (e) {
  console.log(e)
}
```
I commented your code so you can see your mistake

A simpler repro would be:
```js
import { EngineSessionPortParseError } from "@dagger.io/dagger"
```

**Comment by ThyDevourer** [comment]
Hi, @dolanor is right, there are a lot of things in the docs that can't be used right now because they're not exported, one example are Enums, since the following are the only things exported from the module:

```
import Client from "./api/client.gen.js";
export { gql } from "graphql-tag";
export { GraphQLClient } from "graphql-request";
export { connect, ConnectOpts, CallbackFct } from "./connect.js";
export default Client;
//# sourceMappingURL=index.d.ts.map

```

**Comment by TomChv** [comment]
@ThyDevourer This should be fine now, we are exporting everything from client and errors

**Comment by slumbering** [comment]
Should we close this one @TomChv

**Comment by TomChv** [comment]
I'm closing this one since there's no more activities on it and already we fixed by exporting errors from our `index.ts`

I also tried on my own and this code works (it's using module logic but the import works either way)

```ts
import { object, UnknownDaggerError, func } from '@dagger.io/dagger';

@object()
class Test {
  @func()
  test() {
    throw new UnknownDaggerError("test", {})
  }
}
```

Output:

```shell
 /src/e2e-tmp/constructor/defaultFactory/src/index.ts:7                                                                                               
┃     throw new UnknownDaggerError("test", {})                                                                                                         
┃           ^                                                                                                                                          
┃                                                                                                                                                      
┃                                                                                                                                                      
┃ UnknownDaggerError: test                                                                                                                             
┃     at Test.test (/src/e2e-tmp/constructor/defaultFactory/src/index.ts:7:11)                                                                         
┃     at Registry.getResult (/src/e2e-tmp/constructor/defaultFactory/sdk/introspector/registry/registry.ts:131:26)                                     
┃     at invoke (/src/e2e-tmp/constructor/defaultFactory/sdk/entrypoint/invoke.ts:65:31)                                                               
┃     at LogOutput (/src/e2e-tmp/constructor/defaultFactory/sdk/entrypoint/entrypoint.ts:55:24)                                                        
┃     at connection (/src/e2e-tmp/constructor/defaultFactory/sdk/connect.ts:31:3)                                                                      
┃     at entrypoint (/src/e2e-tmp/constructor/defaultFactory/sdk/entrypoint/entrypoint.ts:24:3) {                                                      
┃   cause: undefined,                                                                                                                                  
┃   code: 'D101'                                                                                                                                       
┃ }
```
