### ISSUE TITLE
Dagger execution hangs when invoking func which requires docker socket

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#4673]
Steps to reproduce:

1. Checkout the following branch https://github.com/marcosnils/kubeconeu-question-5/tree/dagger
2. Run `go run ./ci/main.go package` and you'll notice that dagger execution never finishes after displaying something like `#3 11.82 Layer 'buildpacksio/lifecycle:cache.sbom' SHA: sha256:a5cda63693b26825fec73e9367bbf216d1134e8c5d32f0459f568117dea3348b`

Running the same pipeline with `docker` works:

`docker run -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`:/app --workdir /app --rm  ghcr.io/knative/func/func build -v -b pack `

Will finish the execution with the following message: `🙌 Function image built: docker.io/salaboy/kubeconeu-question-5:latest`

Next step is to understand what the `func` binary is actually doing so it never ends when executed in `dagger`

**Comment by sipsma** [comment]
Sending SIGQUIT to the `/ko-app/func` process that's stuck showed that it **might** be stuck still trying to read from the docker container's stdout/stderr, but there's a lot going on there so I'm not sure. Included the stack trace below, see `goroutine 84` specifically.

It would be helpful to see if we can reproduce the behavior in a simpler test case @marcosnils it's possible this is another manifestation of the problems we've experienced previously with the docker cli and proxying stdio over the unix socket.

<details>
<summary>Stack Trace</summary>

```
3 990.7 SIGQUIT: quit
#3 990.7 PC=0x46d741 m=0 sigcode=0
#3 990.7 goroutine 0 [idle]:
#3 990.7 runtime.futex()
#3 990.8        runtime/sys_linux_amd64.s:552 +0x21
#3 990.8 runtime.futexsleep(0x4000800af0?, 0x447213?, 0xc000069900:66?)
#3 990.8        runtime/os_linux.go
#3 990.8 runtime.notesleep(0x3ff0f28)
#3 990.8        runtime/lock_futex.go: +0x36)
#3 990.8        runtime/proc.go:2430159 +0x87
#3 990.8 runtime.mPark()
#3 990.8        runtime/proc.go:1449 +0x25
#3 990.8 runtime.stoplockedm( +0x65
#3 990.8 (runtime.schedule)
#3 990.8        runtime/proc.go: +0x3d
#3 990.8 runtime.park_m3127(0xc0006031e0?)
#3 990.8        runtime/proc.go:3344 +0x14d
#3 990.8 runtime.mcall()
#3 990.8        runtime/asm_amd64.s:425 +0x43
#3 990.8 goroutine 1 [
#3 990.8 chan receive16,  minutes]:
#3 990.8 github.com/buildpacks/pack/internal/container.DefaultHandler.func1(0xc000bd6600, 0xc0000e3aa0, {0x2b037a0?, github.com/buildpacks/pack/internal/container.
RunWithHandler0xc000f56420})
#3 990.8        github.com/buildpacks/pack@v0.28.0/internal/container/run.go:57 +0x245
#3 990.8 ({0x2b2c158, {0xc000484800}, 0x2b54bb8, 0xc00072acf0}, {0xc0012a0140, 0x40}, 0xc000202b70)
#3 990.8 github.com/buildpacks/pack@v0.28.0/internal/container/run.go   :34 +0x204
#3 990.8 github.com/buildpacks/pack/internal/build.(*Phase).Run(0xc0002f02a0, {0x2b2c158, 0xc000484800})
#3 990.8        github.com/buildpacks/pack@v0.28.0/internal/build/phase.go:49 +0x275
#3 990.8 github.com/buildpacks/pack/internal/build.(*LifecycleExecution).Create0xc0005a4480, {0x2b2c158, 0xc000484800}, {0x2b1dbe0, 0xc0000ee100}, {0x2b1dbe0, 0xc0
000ee120(}, {0x2b05400, 0xc000eb60b8})
#3 990.8 (      github.com/buildpacks/pack@v0.28.0/internal/build/lifecycle_execution.go:315 +0x286f
#3 990.8 github.com/buildpacks/pack/internal/build.(*LifecycleExecution).Run0xc0005a4480, {0x2b2c158, 0xc000484800}, 0xc000651ea00x651
#3 990.8 github.com/buildpacks/pack/internal/build.(*LifecycleExecutor).Execute(?)
#3 990.8        github.com/buildpacks/pack@v0.28.0/internal/build/lifecycle_execution.go:209 +_, {_, _}, {{0xc0002bd7cc, 0x4}{, 0x2b332700x2b2fee8, 0xc000651ea0}, 
{, 0xc000ee6780}, {0xc0005e4210, }, ...}...)
#3 990.8        github.com/buildpacks/pack@v0.28.0/internal/build/lifecycle_executor.go:113 +0x1de
#3 990.8 github.com/buildpacks/pack/pkg/client.(*Client).Build(_, {_, _}, {{0x0, 0x0}, {0xc000f5a450, 0x2d}, {0x275b0d9, 0x25}, {0x0, ...}, ...})
#3 990.9        github.com/buildpacks/pack@v0.28.0/pkg/client/build.go395: +0x1f46
#3 990.9 knative.dev/func/pkg/builders/buildpacks.(*Builder).Build(_, {_, _}, {{0xc0002bce08, 0x6}, {0xc0002bccec, 0x4}, {0xc00005b908, 0x14}, {0xc0002bce30, ...},
 ...})
#3 990.9        knative.dev/func/pkg/builders/buildpacks/builder.go
#3 990.9 knative.dev/func/pkg/functions.(*Client).Build(0xc0006ac500, {:159 +0x670, 0xc000bd5f00}, {0x0, 0x0})
#3 990.9 0x2b2c158knative.dev/func/pkg/functions/client.go:661 +0x2c6
#3 990.9 knative.dev/func/cmd.runBuild(0xc0005f4000, {0x0?, 0x0?, 0x0?}, 0x2850d90)
#3 990.9        knative.dev/func/cmd/build.go:196 +0xff1
#3 990.9         +0x25
#3 990.9 knative.dev/func/cmd.NewBuildCmd.func1(0xc0005f4000?, {0xc0005faa20?, 0x3?, 0x3?})
#3 990.9        knative.dev/func/cmd/build.go:69)
#3 990.9        github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
#3 990.9 github.com/spf13/cobra.(*Command).ExecuteC(0xc0009d8300)
#3 990.9        github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bc
#3 990.9 github.com/spf13/cobra.(*Command).Execute(...)
#3 990.9 github.com/spf13/cobra.(*Command).execute(0xc0005f4000, {0xc0005fa9c0, 0x3, 0x3}       github.com/spf13/cobra@v1.6.1/command.go:968
#3 990.9 github.com/spf13/cobra.(*Command).ExecuteContext       github.com/spf13/cobra@v1.6.1/command.go:961
#3 990.9 main.main()
#3 990.9        knative.dev/func/cmd/func/main.go:41 +0x235
#3 990.9 (...)
#3 990.9 github.com/golang/glog.(*loggingT).flushDaemon
#3 990.9 goroutine 18 [chan receive]:
#3 990.9 ?(0x0)
#3 990.9        github.com/golang/glog@v1.0.0/glog.go:882 +0x6a
#3 990.9 created by github.com/golang/glog.init.0
#3 990.9        github.com/golang/glog@v1.0.0/glog.go:410 +0x1bf
#3 990.9 
#3 990.9  [goroutine 19select, 16 minutes]:
#3 990.9 github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc0000e48c0github.com/dgraph-io/ristretto.newDefaultPolicy)
#3 990.9        github.com/dgraph-io/ristretto@v0.1.0/policy.go:102 +0x91
#3 990.9 created by 
#3 990.9        github.com/dgraph-io/ristretto@v0.1.0/policy.go:86 +0x156
#3 990.9 
#3 990.9 goroutine 62 [select]:
#3 990.9 github.com/dgraph-io/ristretto.(*Cache).processItems(0xc0000ea780)
#3 990.9        github.com/dgraph-io/ristretto@v0.1.0/cache.go:452 +
#3 990.9        github.com/dgraph-io/ristretto@v0.1.0/cache.go:403 +0x117
#3 990.9 
#3 990.9 goroutine 6 [select]:
#3 990.9 go.opencensus.io/stats/view.(*worker).start(0xc000c87100)
#3 990.9        go.opencensus.io@v0.24.0/stats/view/worker.go:2920x15e
#3 990.9 created by github.com/dgraph-io/ristretto.(*Cache).Clear +0xad
#3 990.9 created by go.opencensus.io/stats/view.init.0
#3 990.9        go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x8d
#3 990.9 
#3 990.9 goroutine 29main.main.func1( [chan receive, 16 minutes]:
#3 990.9 )
#3 990.9 
#3 990.9        knative.dev/func/cmd/func/main.go:27 +0x2dcreated by  minutesmain.main
#3 990.9        knative.dev/func/cmd/func/main.go:26 +0x13a
#3 990.9 
#3 990.9 goroutine 35 [chan receive, 16]:
#3 990.9 knative.dev/pkg/metrics.(*metricsWorker).start(0xc0002ae040)
#3 990.9        knative.dev/pkg@v0.0.0-20230224190030-645afb2d5dad/metrics/metrics_worker.go:99 +0x2f
#3 990.9 created by os/signal.signal_recv()
#3 990.9        runtime/sigqueue.go:151 +0x2f
#3 990.9 os/signal.loop()
#3 990.9        os/signal/signal_unix.go:23 +knative.dev/pkg/metrics.init.0
#3 990.9        knative.dev/pkg@v0.0.0-20230224190030-645afb2d5dad/metrics/exporter.go:39 +0xae
#3 990.9 
#3 990.9 goroutine 49 [syscall, 16 minutes]:
#3 990.9 0x19
#3 990.9 created by os/signal.Notify.func1.1
#3 990.9        os/signal/signal.go:151 +0x2a
#3 990.9 goroutine 64 [
#3 990.9 IO wait, internal/poll.runtime_pollWait(0x4027641858, 0x72)
#3 990.9 16 minutes]:
#3 990.9 runtime/netpoll.go     302 +0x89
#3 990.9 internal/poll.(*pollDesc).wait(0xc0000ea980?, 0xc000862000?, 0x0)
#3 990.9        internal/poll/fd_poll_runtime.go:83 +0x32
#3 990.9 internal/poll.(*pollDesc).waitRead(...)
#3 990.9        internal/poll/fd_poll_runtime.go:88
#3 990.9 internal/poll.(*FD).Read(:, 0xc0000ea980, {0xc000862000, 0x10000x1000})
#3 990.9        internal/poll/fd_unix.go:
#3 990.9 167 +0x25anet.(*netFD).Read(0xc0000ea980, {0xc000862000?, ?0x405f09{, 0x4?})
#3 991.0        net/fd_posix.go:55 +0x29
#3 991.0 net.(*conn).Read(0xc0002ae128, )
#3 991.0        0xc000862000?, 0x0?, 0x0?}net/net.go: +0x45
#3 991.0 net/http.(*persistConn).Read(183?})
#3 991.0        net/http/transport.go:1929 +0x4e
#3 991.0 bufio.(*Reader).fill(0xc000f633e0)
#3 991.0        bufio/bufio.go:106 +0x103
#3 991.0 0xc000b01d40, {0xc000862000?, 0xc0002da0c0?, 0xc0000c1d30(bufio.(*Reader).Peek0x10xc000f633e0, )
#3 991.0        bufio/bufio.go144 +0x5d
#3 991.0 net/http.(*persistConn).readLoop(0xc000b01d40)
#3 991.0        net/http/transport.go:2093 +0x1ac
#3 991.0 created by net/http.(*Transport).dialConn
#3 991.0        net/http/transport.go:1750 +0x173e
#3 991.0 
#3 991.0 goroutine 65 [select, 16 minutes]:
#3 991.0 net/http.(*persistConn).writeLoop:(0xc000b01d40)
#3 991.0        net/http/transport.go:2392 +0xf5
#3 991.0 created by net/http.(*Transport).dialConn
#3 991.0        net/http/transport.go:1751 +0x1791
#3 991.0 
#3 991.0 goroutine 99 [IO wait, 16 minutes]:
#3 991.0 internal/poll.runtime_pollWait(0x4027641678, 0x72)
#3 991.0        runtime/netpoll.go:302 +0x89
#3 991.0 internal/poll.(*pollDesc).wait(0xc0002c2600?, 0xc000c47000?, 0x0)
#3 991.0        internal/poll/fd_poll_runtime.go:83 +0x32
#3 991.0 internal/poll.(*pollDesc).waitRead(...)
#3 991.0        internal/poll/fd_poll_runtime.go:88
#3 991.0 internal/poll.(*FD).Read(0xc0002c2600, {0xc000c47000, 0x1000, 0x1000})
#3 991.0        internal/poll/fd_unix.go:167 +0x25a
#3 991.0 net.(*netFD).Read(0xc0002c2600, {0xc000c47000?, 0x0?, 0x4?})
#3 991.0        net/fd_posix.go:55 +0x29
#3 991.0 net.(*conn).Read(0xc0002ae408, {0xc000c47000?, 0xc0002ae3e8?, 0x1?})
#3 991.0        net/net.go:183 +0x45
#3 991.0 net/http.(*persistConn).Read(0xc000f4e000, {0xc000c47000?, 0x44b9c0?, 0xc00109fec8net/http/transport.go?})
#3 991.0        :1929 +0x4e
#3 991.0 bufio.(*Reader).fill(0xc000f56a20)
#3 991.0        bufio/bufio.go:106 +0x103
#3 991.0 bufio.(*Reader).Peek(0xc000f56a20, 0x1)
#3 991.0        bufio/bufio.go:144 +0x5d
#3 991.0 net/http.(*persistConn).readLoop(0xc000f4e000)
#3 991.0        net/http/transport.go:2093 +0x1ac
#3 991.0 created by net/http.(*Transport).dialConn
#3 991.0        net/http/transport.go:1750 +0x173e
#3 991.0 
#3 991.0 goroutine 100 [select, 16 minutes]:
#3 991.0 net/http.(*persistConn).writeLoop(0xc000f4e000)
#3 991.0        net/http/transport.go:2392 +0xf5
#3 991.0 created by net/http.(*Transport).dialConn
#3 991.0        net/http/transport.go:1751 +0x1791
#3 991.0 
#3 991.0 goroutine 84 [IO wait, 16 minutes]:
#3 991.0 internal/poll.runtime_pollWait(0x4027641768, 0x72)
#3 991.0        runtime/netpoll.go:302 +0x89
#3 991.0 internal/poll.(*pollDesc).wait(0xc0002c2280?, 0xc0010a0000?internal/poll/fd_poll_runtime.go, 0x0)
#3 991.0        :83 +0x32
#3 991.0 internal/poll.(*pollDesc).waitRead(...)
#3 991.0        internal/poll/fd_poll_runtime.go:88
#3 991.0 internal/poll.(*FD).Read(0xc0002c2280, {0xc0010a0000, 0x8009, 0x8009})
#3 991.0        internal/poll/fd_unix.go:167 +0x25a
#3 991.0 , 0x0?}net.(*netFD).Read(0xc0002c2280, {0xc0010a0000?, 0xc0010a0008?)
#3 991.0        net/fd_posix.go:55 +0x29
#3 991.0 net.(*conn).Read(0xc0002ae388, {0xc0010a0000?, 0x2235800?, 0xc0000dc7e0?}      )
#3 991.0 net/net.go:183 +0x45
#3 991.0 })
#3 991.0        bufio.(*Reader).Read(0xc000f56420, {0xc0010a0000, 0x8009, 0x0?bufio/bufio.go:222 +0x106
#3 991.0 github.com/docker/docker/pkg/stdcopy.StdCopy({0x2b05640, 0xc001230cf0}, {0x2b05640, 0xc001230d20}, {0x2b037a0, 0xc000f56420})
#3 991.0        github.com/docker/docker@v20.10.21+incompatible/pkg/stdcopy/stdcopy.go:108 +0x444
#3 991.0 github.com/buildpacks/pack/internal/container.DefaultHandler.func1.1()
#3 991.0        github.com/buildpacks/pack@v0.28.0/internal/container/run.go:41 +0x74
#3 991.0 created by github.com/buildpacks/pack/internal/container.DefaultHandler.func1
#3 991.0        github.com/buildpacks/pack@v0.28.0/internal/container/run.go:40 +0x13d
```

</details>

**Comment by mircubed** [comment]
@marcosnils do you mind assigning this to yourself, or is there someone else that should work on it?

**Comment by marcosnils** [comment]
I can check it out.

**Comment by marcosnils** [comment]
found what's causing  this but I don't know why yet
been debugging func's code and I reached up to this part where containers are spawned: 

https://github.com/buildpacks/pack/blob/main/internal/build/phase.go#L32

^ container is created

https://github.com/buildpacks/pack/blob/main/internal/build/phase.go#L48-L55

^ container is started with a special out/err stream handler here

https://github.com/buildpacks/pack/blob/main/internal/container/run.go#L43-L65

^ this is the special stream handler that's causing the actual issue. I replaced that DefaultHandler with a noop one and it works ok 
I'm coming up with a simple repro

**Comment by marcosnils** [comment]
Ok, finally managed to repro this:

--main.go--
```go
package main

import (
	"context"
	"fmt"
	"io"
	"os"

	"github.com/docker/docker/api/types"
	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/client"
	"github.com/docker/docker/pkg/stdcopy"
	"github.com/pkg/errors"
)

type Handler func(bodyChan <-chan container.ContainerWaitOKBody, errChan <-chan error, reader io.Reader) error

func main() {
	cli, err := client.NewClientWithOpts(client.FromEnv)
	if err != nil {
		panic(err)
	}

	ctx := context.Background()

	ctr, err := cli.ContainerCreate(ctx, &container.Config{
		User:  "root",
		Cmd:   []string{"ls", "-l", "/"},
		Image: "alpine",
	}, &container.HostConfig{}, nil, nil, "")

	bodyChan, errChan := cli.ContainerWait(ctx, ctr.ID, container.WaitConditionNextExit)

	resp, err := cli.ContainerAttach(ctx, ctr.ID, types.ContainerAttachOptions{
		Stream: true,
		Stdout: true,
		Stderr: true,
	})
	if err != nil {
		panic(err)
	}
	defer resp.Close()

	if err := cli.ContainerStart(ctx, ctr.ID, types.ContainerStartOptions{}); err != nil {
		panic(errors.Wrap(err, "container start"))
	}

	err = DefaultHandler(os.Stdout, os.Stderr)(bodyChan, errChan, resp.Reader)
	if err != nil {
		panic(err)
	}

	// return handler(bodyChan, errChan, resp.Reader)
}

func DefaultHandler(out, errOut io.Writer) Handler {
	return func(bodyChan <-chan container.ContainerWaitOKBody, errChan <-chan error, reader io.Reader) error {
		copyErr := make(chan error)
		go func() {
			_, err := stdcopy.StdCopy(out, errOut, reader)
			defer optionallyCloseWriter(out)
			defer optionallyCloseWriter(errOut)

			copyErr <- err
		}()

		select {
		case body := <-bodyChan:
			if body.StatusCode != 0 {
				return fmt.Errorf("failed with status code: %d", body.StatusCode)
			}
		case err := <-errChan:
			return err
		}

		return <-copyErr
	}
}

func optionallyCloseWriter(writer io.Writer) error {
	if closer, ok := writer.(io.Closer); ok {
		return closer.Close()
	}

	return nil
}
```
--ci/main.go--
```go
package main

import (
	"context"
	"fmt"
	"os"

	"dagger.io/dagger"
)

func main() {
	ctx := context.Background()

	c, err := dagger.Connect(ctx, dagger.WithLogOutput(os.Stderr))
	if err != nil {
		panic(err)
	}

	dockerSock := c.Host().UnixSocket("/var/run/docker.sock")
	bin := c.Host().Workdir(dagger.HostWorkdirOpts{
		Include: []string{"main"},
	}).File("main")

	out, err := c.Container().
		WithUnixSocket("/var/run/docker.sock", dockerSock).
		WithMountedFile("/main", bin).
		WithExec([]string{"/main"}).Stdout(ctx)
	if err != nil {
		panic(err)
	}

	fmt.Println(out)
}
```

^ when running `ci/main.go` with the binary from `./main.go`, you'll notice that the program never ends. However, when executed using `docker run -v `pwd`/main:/main -v /var/run/docker.sock:/var/run/docker.sock test /main`, the program finishes successfully.

@sipsma is there anything preliminary that brings your attention? I'll start diving into dagger to understand what's happening from our side.

**Comment by sipsma** [comment]
@marcosnils thanks for the simpler reproducer, I poked at this for a little bit but am more confused than when I started now.

I was wondering if we just needed to propagate a close of the docker container conn to the buildkit client, so I made that change along with a few other println debugs here: https://github.com/sipsma/dagger/commit/0ee831ff343861718d4346951d6f302889c95b55

The first weird thing is that while most of the time I still get a hang when running with that branch, I occasionally will no longer get one and have to delete the engine's cache in order to get the behavior again.

The second weird thing is that my println debugs show this when there is a hang:
```
starting copy of socket connection for socket:eyJob3N0X3BhdGgiOiIvcnVuL2RvY2tlci5zb2NrIn0=
starting copy of socket connection for socket:eyJob3N0X3BhdGgiOiIvcnVuL2RvY2tlci5zb2NrIn0=
starting copy of socket connection for socket:eyJob3N0X3BhdGgiOiIvcnVuL2RvY2tlci5zb2NrIn0=
closing socket connection for socket:eyJob3N0X3BhdGgiOiIvcnVuL2RvY2tlci5zb2NrIn0=
#3 0.481 total 56
#3 0.481 drwxr-xr-x    2 root     root          4096 Nov 22 13:08 bin
#3 0.481 drwxr-xr-x    5 root     root           340 Mar 13 22:53 dev
#3 0.481 drwxr-xr-x    1 root     root          4096 Mar 13 22:53 etc
#3 0.481 drwxr-xr-x    2 root     root          4096 Nov 22 13:08 home
#3 0.481 drwxr-xr-x    7 root     root          4096 Nov 22 13:08 lib
#3 0.481 drwxr-xr-x    5 root     root          4096 Nov 22 13:08 media
#3 0.481 drwxr-xr-x    2 root     root          4096 Nov 22 13:08 mnt
#3 0.481 drwxr-xr-x    2 root     root          4096 Nov 22 13:08 opt
#3 0.481 dr-xr-xr-x  265 root     root             0 Mar 13 22:53 proc
#3 0.481 drwx------    2 root     root          4096 Nov 22 13:08 root
#3 0.481 drwxr-xr-x    2 root     root          4096 Nov 22 13:08 run
#3 0.481 drwxr-xr-x    2 root     root          4096 Nov 22 13:08 sbin
#3 0.481 drwxr-xr-x    2 root     root          4096 Nov 22 13:08 srv
#3 0.481 dr-xr-xr-x   13 root     root             0 Mar 13 22:53 sys
#3 0.481 drwxrwxrwt    2 root     root          4096 Nov 22 13:08 tmp
#3 0.481 drwxr-xr-x    7 root     root          4096 Nov 22 13:08 usr
#3 0.481 drwxr-xr-x   12 root     root          4096 Nov 22 13:08 var
```

What I don't understand immediately is why there are **3** instances of forwarding the docker socket; I only expected there to be 1 since there's only 1 exec being evaluated. Maybe I'm forgetting something but that seems wrong.

I think a good next step would be to understand why the socket is being forwarded from 3 instances.

**Comment by marcosnils** [comment]
@sipsma if @matiasinsaurralde has some bandwidth maybe he can help to follow-up this trick issue?

**Comment by bonilla-cesar** [comment]
hey folks I am having the same issue on dagger-go-sdk@v0.11.6 any plans of tackling this issue any time soon?
