### ISSUE TITLE
🐞 Trying to RUN a directory (instead of a file) seems to crash buildkit.

### ISSUE THREAD

**Issue by chakrit** [dagger/dagger#4965]
### What is the issue?

Running a directory (by mistake, not by intention) seems to cause the build process to crash or exit prematurely.

Check the "Steps to reproduce" for the dagger script I've used. The equivalent Dockerfile correctly aborts with Permission denied error:

```
 => [2/3] RUN mkdir -p /test/abc                                                                                    0.2s
 => ERROR [3/3] RUN /test/abc                                                                                       0.3s
------
 > [3/3] RUN /test/abc:
#6 0.292 /bin/sh: /test/abc: Permission denied
```

### Log output

```
Traceback (most recent call last):
  File "/Users/chakrit/.pyenv/versions/3.10.1/lib/python3.10/site-packages/dagger/api/base.py", line 153, in _handle_execute
    yield
  File "/Users/chakrit/.pyenv/versions/3.10.1/lib/python3.10/site-packages/dagger/api/base.py", line 106, in execute_sync
    result = self.session.execute(query)
  File "/Users/chakrit/.pyenv/versions/3.10.1/lib/python3.10/site-packages/gql/client.py", line 860, in execute
    raise TransportQueryError(
gql.transport.exceptions.TransportQueryError: {'message': 'failed to solve: process "/test/abc" did not complete successfully: exit code: 1', 'locations': [{'line': 6, 'column': 11}], 'path': ['container', 'from', 'withExec', 'withExec', 'export']}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/private/tmp/xxx/build.py", line 9, in <module>
    container.export('test.docker')
  File "/Users/chakrit/.pyenv/versions/3.10.1/lib/python3.10/site-packages/dagger/api/base.py", line 304, in wrapper
    return bear(*args, **kwargs)
  File "<@beartype(dagger.api.gen_sync.Container.export) at 0x10238f6d0>", line 65, in export
  File "/Users/chakrit/.pyenv/versions/3.10.1/lib/python3.10/site-packages/dagger/api/gen_sync.py", line 398, in export
    return _ctx.execute_sync(bool)
  File "/Users/chakrit/.pyenv/versions/3.10.1/lib/python3.10/site-packages/dagger/api/base.py", line 105, in execute_sync
    with self._handle_execute(query):
  File "/Users/chakrit/.pyenv/versions/3.10.1/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/chakrit/.pyenv/versions/3.10.1/lib/python3.10/site-packages/dagger/api/base.py", line 179, in _handle_execute
    raise error from e
dagger.exceptions.QueryError: failed to solve: process "/test/abc" did not complete successfully: exit code: 1
```

And docker logging the engine gives:

```
time="2023-04-16T11:40:22Z" level=error msg="/moby.buildkit.v1.frontend.LLBBridge/Solve returned error: rpc error: code = Unknown desc = process \"/test/abc\" did not complete successfully: exit code: 1"
process "/test/abc" did not complete successfully: exit code: 1
1 v0.0.0+unknown /usr/local/bin/dagger-engine --config /etc/dagger/engine.toml --debug
github.com/moby/buildkit/executor/runcexecutor.exitError
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/executor/runcexecutor/executor.go:328
github.com/moby/buildkit/executor/runcexecutor.(*runcExecutor).Run
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/executor/runcexecutor/executor.go:302
github.com/moby/buildkit/solver/llbsolver/ops.(*ExecOp).Exec
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/solver/llbsolver/ops/exec.go:360
github.com/moby/buildkit/solver.(*sharedOp).Exec.func2
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/solver/jobs.go:900
github.com/moby/buildkit/util/flightcontrol.(*call).run
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/util/flightcontrol/flightcontrol.go:121
sync.(*Once).doSlow
        /usr/local/go/src/sync/once.go:74
sync.(*Once).Do
        /usr/local/go/src/sync/once.go:65
runtime.goexit
        /usr/local/go/src/runtime/asm_arm64.s:1172

1 v0.0.0+unknown /usr/local/bin/dagger-engine --config /etc/dagger/engine.toml --debug
github.com/moby/buildkit/solver/llbsolver/ops.(*ExecOp).Exec
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/solver/llbsolver/ops/exec.go:380
github.com/moby/buildkit/solver.(*sharedOp).Exec.func2
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/solver/jobs.go:900
github.com/moby/buildkit/util/flightcontrol.(*call).run
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/util/flightcontrol/flightcontrol.go:121
sync.(*Once).doSlow
        /usr/local/go/src/sync/once.go:74
sync.(*Once).Do
        /usr/local/go/src/sync/once.go:65
runtime.goexit
        /usr/local/go/src/runtime/asm_arm64.s:1172

1 v0.0.0+unknown /usr/local/bin/dagger-engine --config /etc/dagger/engine.toml --debug
github.com/moby/buildkit/solver.(*edge).execOp
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/solver/edge.go:906
github.com/moby/buildkit/solver/internal/pipe.NewWithFunction.func2
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/solver/internal/pipe/pipe.go:82
runtime.goexit
        /usr/local/go/src/runtime/asm_arm64.s:1172

1 v0.0.0+unknown /usr/local/bin/dagger-engine --config /etc/dagger/engine.toml --debug
main.unaryInterceptor.func1
        /app/cmd/engine/main.go:656
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34
github.com/moby/buildkit/frontend/gateway/pb._LLBBridge_Solve_Handler
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/frontend/gateway/pb/gateway.pb.go:3083
google.golang.org/grpc.(*Server).processUnaryRPC
        /go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1336
google.golang.org/grpc.(*Server).handleStream
        /go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1704
google.golang.org/grpc.(*Server).serveStreams.func1.2
        /go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:965
runtime.goexit
        /usr/local/go/src/runtime/asm_arm64.s:1172

time="2023-04-16T11:40:22Z" level=error msg="/moby.buildkit.v1.Control/Solve returned error: rpc error: code = Unknown desc = process \"/test/abc\" did not complete successfully: exit code: 1"
process "/test/abc" did not complete successfully: exit code: 1
1 v0.0.0+unknown /usr/local/bin/dagger-engine --config /etc/dagger/engine.toml --debug
github.com/moby/buildkit/executor/runcexecutor.exitError
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/executor/runcexecutor/executor.go:328
github.com/moby/buildkit/executor/runcexecutor.(*runcExecutor).Run
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/executor/runcexecutor/executor.go:302
github.com/moby/buildkit/solver/llbsolver/ops.(*ExecOp).Exec
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/solver/llbsolver/ops/exec.go:360
github.com/moby/buildkit/solver.(*sharedOp).Exec.func2
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/solver/jobs.go:900
github.com/moby/buildkit/util/flightcontrol.(*call).run
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/util/flightcontrol/flightcontrol.go:121
sync.(*Once).doSlow
        /usr/local/go/src/sync/once.go:74
sync.(*Once).Do
        /usr/local/go/src/sync/once.go:65
runtime.goexit
        /usr/local/go/src/runtime/asm_arm64.s:1172

1 v0.0.0+unknown /usr/local/bin/dagger-engine --config /etc/dagger/engine.toml --debug
github.com/moby/buildkit/solver/llbsolver/ops.(*ExecOp).Exec
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/solver/llbsolver/ops/exec.go:380
github.com/moby/buildkit/solver.(*sharedOp).Exec.func2
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/solver/jobs.go:900
github.com/moby/buildkit/util/flightcontrol.(*call).run
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/util/flightcontrol/flightcontrol.go:121
sync.(*Once).doSlow
        /usr/local/go/src/sync/once.go:74
sync.(*Once).Do
        /usr/local/go/src/sync/once.go:65
runtime.goexit
        /usr/local/go/src/runtime/asm_arm64.s:1172

1 v0.0.0+unknown /usr/local/bin/dagger-engine --config /etc/dagger/engine.toml --debug
github.com/moby/buildkit/solver.(*edge).execOp
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/solver/edge.go:906
github.com/moby/buildkit/solver/internal/pipe.NewWithFunction.func2
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/solver/internal/pipe/pipe.go:82
runtime.goexit
        /usr/local/go/src/runtime/asm_arm64.s:1172

48168  /Users/chakrit/Library/Caches/dagger/dagger-0.5.0 session --label dagger.io/sdk.name:python --label dagger.io/sdk.version:0.5.1 --label dagger.io/sdk.async:false
google.golang.org/grpc.getChainUnaryInvoker.func1
        /go/pkg/mod/google.golang.org/grpc@v1.53.0/clientconn.go:361
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryClientInterceptor.func1
        /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.40.0/interceptor.go:99
github.com/moby/buildkit/client.filterInterceptor.func1
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/client/client.go:370
google.golang.org/grpc.chainUnaryClientInterceptors.func1
        /go/pkg/mod/google.golang.org/grpc@v1.53.0/clientconn.go:349
google.golang.org/grpc.(*ClientConn).Invoke
        /go/pkg/mod/google.golang.org/grpc@v1.53.0/call.go:35
github.com/moby/buildkit/frontend/gateway/pb.(*lLBBridgeClient).Solve
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/frontend/gateway/pb/gateway.pb.go:2849
github.com/moby/buildkit/client.(*gatewayClientForBuild).Solve
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/client/build.go:89
github.com/moby/buildkit/frontend/gateway/grpcclient.(*grpcClient).Solve
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/frontend/gateway/grpcclient/client.go:411
github.com/dagger/dagger/core.(*Container).export.func1
        /app/core/container.go:1609
github.com/dagger/dagger/core.WithServices[...]
        /app/core/service.go:132
github.com/dagger/dagger/core.(*Container).export
        /app/core/container.go:1595
github.com/dagger/dagger/core.(*Container).Export.func2
        /app/core/container.go:1359
github.com/moby/buildkit/frontend/gateway/grpcclient.(*grpcClient).Run
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/frontend/gateway/grpcclient/client.go:214
github.com/moby/buildkit/client.(*Client).Build.func2
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/client/build.go:59
github.com/moby/buildkit/client.(*Client).solve.func3
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/client/solve.go:283
golang.org/x/sync/errgroup.(*Group).Go.func1
        /go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75
runtime.goexit
        /usr/local/go/src/runtime/asm_arm64.s:1172

1 v0.0.0+unknown /usr/local/bin/dagger-engine --config /etc/dagger/engine.toml --debug
github.com/moby/buildkit/frontend/gateway.(*llbBridgeForwarder).Return
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/frontend/gateway/gateway.go:886
github.com/moby/buildkit/control/gateway.(*GatewayForwarder).Return
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/control/gateway/gateway.go:135
github.com/moby/buildkit/frontend/gateway/pb._LLBBridge_Return_Handler.func1
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/frontend/gateway/pb/gateway.pb.go:3189
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1
        /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.40.0/interceptor.go:342
main.unaryInterceptor.func1
        /app/cmd/engine/main.go:652
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34
github.com/moby/buildkit/frontend/gateway/pb._LLBBridge_Return_Handler
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/frontend/gateway/pb/gateway.pb.go:3191
google.golang.org/grpc.(*Server).processUnaryRPC
        /go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1336
google.golang.org/grpc.(*Server).handleStream
        /go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1704
google.golang.org/grpc.(*Server).serveStreams.func1.2
        /go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:965
runtime.goexit
        /usr/local/go/src/runtime/asm_arm64.s:1172

1 v0.0.0+unknown /usr/local/bin/dagger-engine --config /etc/dagger/engine.toml --debug
main.unaryInterceptor.func1
        /app/cmd/engine/main.go:656
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1
        /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34
github.com/moby/buildkit/api/services/control._Control_Solve_Handler
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230331212110-3187d2d056de/api/services/control/control.pb.go:2440
google.golang.org/grpc.(*Server).processUnaryRPC
        /go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1336
google.golang.org/grpc.(*Server).handleStream
        /go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1704
google.golang.org/grpc.(*Server).serveStreams.func1.2
        /go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:965
runtime.goexit
        /usr/local/go/src/runtime/asm_arm64.s:1172
```

### Steps to reproduce

```python
import dagger

with dagger.Connection(dagger.Config()) as conn:
    container = (
        conn.container().from_("alpine:edge")
        .with_exec(["mkdir", "-p", "/test/abc"])
        .with_exec(["/test/abc"])
    )
    container.export('test.docker')
```

Then run:
```sh
python3 build.py
```

### SDK version

Python SDK v0.5.1

### OS version

Darwin GZ44.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103 arm64

**Comment by chakrit** [comment]
I'm not sure if this is by-design but it seems weird as the user is just shown the `exitcode 1` problem and there's no mention of "permission denied" error here.

**Comment by marcosnils** [comment]
> I'm not sure if this is by-design but it seems weird as the user is just shown the `exitcode 1` problem and there's no mention of "permission denied" error here.

If you check the complete Dockerfile error, you'll see that buildkit outputs that `/bin/sh -c /test/abc` is effectively throwing a "permission denied error"

```
 => [2/3] RUN mkdir -p /test/abc                                                                      0.2s
 => ERROR [3/3] RUN /test/abc                                                                         0.3s
------
 > [3/3] RUN /test/abc:
#0 0.306 /bin/sh: /test/abc: Permission denied
------
Dockerfile:5
--------------------
   3 |     
   4 |     RUN mkdir -p /test/abc
   5 | >>> RUN /test/abc
   6 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c /test/abc" did not complete successfully: exit code: 126
```

That's because you're using the `RUN` instruction in shell mode which basically adds a `sh -c` to your command. If you change your run instruction to `RUN ["/test/abc"]` which doesn't invoke a shell, you'll get the same error as dagger.

Consequently, if you change your dagger pipeline to use `sh -c` the same way as buildkit, you'll get the same error indeed

```python
import dagger
import sys

with dagger.Connection(dagger.Config(log_output=sys.stderr)) as conn:
    container = (
        conn.container().from_("alpine:edge")
        .with_exec(["mkdir", "-p", "/test/abc"])
        .with_exec(["sh", "-c", "/test/abc"])
    )
    container.export('test.docker')

```

this doesn't seem to be an issue. Feel free to close this thread if you think this has been replied :pray:

**Comment by chakrit** [comment]
> RUN ["/test/abc"] which doesn't invoke a shell, you'll get the same error as dagger.

Oh I didn't realize this. However, in dagger we're always using the `[""]` form isn't it? So it's not entirely obvious there. There could be a number of reasons why a process would exit 1.

Would it be possible to catch this somehow? Modify the error message a bit? Or something in the docs would help. I can contribute here if someone could point me in the right direction.

**Comment by mircubed** [comment]
@sipsma assigning to you in case you have some additional context to share :)

**Comment by gerhard** [comment]
As this is related to errors, could this also be linked to our today's error handling discussion @helderco?

**Comment by helderco** [comment]
> As this is related to errors, could this also be linked to our today's error handling discussion @helderco?

No, that's a different thing: https://github.com/dagger/dagger/issues/4700

**Comment by TomChv** [comment]
It seems that the latest version of Dagger fixed this issue.

```
┃ │ │ │ │ Please visit https://dagger.io/help#go for troubleshooting guidance.                                                                                                        
┃ │ │ │ │ exit status 1                                                                                                                                                               
│ █ │ │ │ [0.09s] ERROR exec /test/abc
│ ┃ │ │ │ panic: fork/exec /test/abc: permission denied                                                                                                                               
│ ┃ │ │ │                                                                                                                                                                             
│ ┃ │ │ │ goroutine 1 [running, locked to thread]:                                                                                                                                    
│ ┃ │ │ │ main.shim()                                                                                                                                                                 
│ ┃ │ │ │         /app/cmd/shim/main.go:267 +0xd40                                                                                                                                    
│ ┃ │ │ │ main.main()                                                                                                                                                                 
│ ┃ │ │ │         /app/cmd/shim/main.go:64 +0x7c                                                                                                                                      
│ ┻ │ │ │ 
│   █◀╯ │ [0.09s] ERROR exec banana
│   ┃   │ panic: exec: "banana": executable file not found in $PATH                                                                                                                   
│   ┃   │                                                                                                                                                                             
│   ┃   │ goroutine 1 [running, locked to thread]:                                                                                                                                    
│   ┃   │ main.shim()                                                                                                                                                                 
│   ┃   │         /app/cmd/shim/main.go:267 +0xd40                                                                                                                                    
│   ┃   │ main.main()                                                                                                                                                                 
│   ┃   │         /app/cmd/shim/main.go:64 +0x7c                                                                                                                                      
│   ┻   │ 
│       █ [0.09s] ERROR exec /usr/bin/banana
│       ┃ panic: fork/exec /usr/bin/banana: permission denied                                                                                                                         
│       ┃                                                                                                                                                                             
│       ┃ goroutine 1 [running, locked to thread]:                                                                                                                                    
│       ┃ main.shim()                                                                                                                                                                 
│       ┃         /app/cmd/shim/main.go:267 +0xd40                                                                                                                                    
│       ┃ main.main()                                                                                                                                                                 
│       ┃         /app/cmd/shim/main.go:64 +0x7c                                                                                                                                      
┻       ┻ 
WARNING: Using development engine; skipping version compatibility check.   
```

Should we close this issue?

**Comment by TomChv** [comment]
I'm closing this issue since the latest version of dagger really improved the error messaging.

Here's a simple repro based on Python SDK v0.8.7


Create a python file, for instance I named it `repro-4965.py` with your repro as content:
```python
import anyio

import dagger


async def test():
    async with dagger.Connection(dagger.Config()) as conn:
        await conn.container().from_("alpine:edge").with_exec(["mkdir", "-p", "/test/abc"]).with_exec(["/test/abc"]).stdout()


anyio.run(test)
```

Execute dagger

```shell
# setup venv
python3 -m venv .venv && source .venv/bin/activate

# Install dagger-io latest version (currently 0.8.7)
pip install dagger-io==0.8.7

# Run dagger using dagger run (make sure you have the latest CLI installed)
dagger run python repro-4965.py
```

Output:
```shell
  █ [0.10s] ERROR exec /test/abc
  ┃ panic: fork/exec /test/abc: permission denied                                                                                                            
  ┃                                                                                                                                                          
  ┃ goroutine 1 [running, locked to thread]:                                                                                                                 
  ┃ main.shim()                                                                                                                                              
  ┃         /app/cmd/shim/main.go:267 +0xd40                                                                                                                 
  ┃ main.main()                                                                                                                                              
  ┃         /app/cmd/shim/main.go:64 +0x7c                                                                                                                   
  ┻ 
• Engine: 3a552ab9f2d7 (version main)
⧗ 4.97s ✔ 14 ✘ 4
```

Feel free to reopen it @chakrit if I missed something

**Comment by chakrit** [comment]
@TomChv that's on par with docker so i think it's ok. at least it shouldn't just crash. sh does it a little better saying `./abc: is a directory` but I don't think we need to go out of our way to support that.

**Comment by TomChv** [comment]
If you power up a container with `sh`, it might also returns this error @chakrit
