### ISSUE TITLE
🐞 TUI display incorrect when sdk crash with exception

### ISSUE THREAD

**Issue by wingyplus** [dagger/dagger#5191]
### What is the issue?

From https://github.com/wingyplus/kaogeek-discord-bot/tree/dagger/deployment

I accidentally set export to `docker.io/kaogeek` and found crash when running in auto provisioning mode. When running with TUI feature I see all pass at first but it hide the crash log in the first step and step export not show in the TUI. I expected to see the step is a failure at least and may show the export step failure, this could spot the problems more easier.

### Log output

Auto provisioning mode:

```
file:///Users/thanabodee/src/github.com/creatorsgarten/kaogeek-discord-bot/deployment/node_modules/.pnpm/@dagger.io+dagger@0.5.3/node_modules/@dagger.io/dagger/dist/api/utils.js:144
                throw new GraphQLRequestError("Error message", {
                      ^

GraphQLRequestError: Error message
    at file:///Users/thanabodee/src/github.com/creatorsgarten/kaogeek-discord-bot/deployment/node_modules/.pnpm/@dagger.io+dagger@0.5.3/node_modules/@dagger.io/dagger/dist/api/utils.js:144:23
    at Generator.throw (<anonymous>)
    at rejected (file:///Users/thanabodee/src/github.com/creatorsgarten/kaogeek-discord-bot/deployment/node_modules/.pnpm/@dagger.io+dagger@0.5.3/node_modules/@dagger.io/dagger/dist/api/utils.js:5:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: ClientError: open /Users/thanabodee/src/github.com/creatorsgarten/kaogeek-discord-bot/deployment/docker.io/kaogeek: no such file or directory: {"response":{"data":null,"errors":[{"message":"open /Users/thanabodee/src/github.com/creatorsgarten/kaogeek-discord-bot/deployment/docker.io/kaogeek: no such file or directory","locations":[{"line":2,"column":58719}],"path":....
```

TUI:

<img width="1915" alt="Screenshot 2566-05-25 at 09 57 48" src="https://github.com/dagger/dagger/assets/484530/47d5de01-a842-41cc-81a0-40d833afffd0">

### Steps to reproduce

Provisioning mode run by `pnpm build`. And TUI mode run with `_EXPERIMENT_DAGGER_TUI=1 dagger run pnpm run build`.

### SDK version

0.5.3

### OS version

macOS 13.1 (22C65)

**Comment by gerhard** [comment]
I **think** that this one is duplicate of https://github.com/dagger/dagger/issues/5150. WDYT @vito?

**Comment by vito** [comment]
@gerhard Hard to say, this one's a bit easier to tell what went wrong so I addressed it in #5232
