### ISSUE TITLE
🐞 Unable to get digest of GitRef

### ISSUE THREAD

**Issue by bakhtin** [dagger/dagger#5367]
### What is the issue?

Calling `digest()` on a GitRef object instance fails with `dagger.exceptions.QueryError: not implemented yet` exception

### Log output

```
Connected to engine 974d679fe8b2
Traceback (most recent call last):
  File "<PATH>/lib/python3.10/site-packages/dagger/api/base.py", line 170, in _handle_execute
    yield
  File "<PATH>/lib/python3.10/site-packages/dagger/api/base.py", line 107, in execute
    result = await self.session.execute(query)
  File "<PATH>/lib/python3.10/site-packages/gql/client.py", line 1231, in execute
    raise TransportQueryError(
gql.transport.exceptions.TransportQueryError: {'message': 'not implemented yet', 'locations': [{'line': 4, 'column': 7}], 'path': ['git', 'branch', 'digest']}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<PATH>/.github/workflows/minimal.py", line 13, in <module>
    anyio.run(main)
  File "<PATH>/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "<PATH>/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "<PATH>/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "<PATH>/.github/workflows/minimal.py", line 10, in main
    git_digest = await client.git("https://github.com/dagger/examples.git").branch("main").digest()
  File "<@beartype(dagger.api.gen.GitRef.digest) at 0x7f282ca6f6d0>", line 10, in digest
  File "<PATH>/lib/python3.10/site-packages/dagger/api/gen.py", line 2155, in digest
    return await _ctx.execute(str)
  File "<PATH>/lib/python3.10/site-packages/dagger/api/base.py", line 106, in execute
    with self._handle_execute(query):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "<PATH>/lib/python3.10/site-packages/dagger/api/base.py", line 196, in _handle_execute
    raise error from e
dagger.exceptions.QueryError: not implemented yet
```

### Steps to reproduce

```python3
import sys, anyio, dagger

async def main():
  config = dagger.Config(log_output=sys.stdout)

  async with dagger.Connection(config) as client:
    git_digest = await client.git("https://github.com/dagger/examples.git").branch("main").digest()
    print(git_digest)

anyio.run(main)
```

### SDK version

Python SDK v0.6.2

### OS version

Linux Mint 21.1, Python 3.10

**Comment by helderco** [comment]
It's confusing that we have fields that aren't implemented so I've removed them:
- https://github.com/dagger/dagger/pull/5410
