### ISSUE TITLE
🐞 Node.js: `envVariable` and `label` raise an error on successful response

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#5482]
### What is the issue?

I'm getting errors with simple `envVariable` and `label` usage, but the response in the error looks legit.

```ts
import Client, { connect } from "@dagger.io/dagger"

connect(async (client: Client) => {
  console.log(await client.container().from("alpine").envVariable("PATH"))
})
```

### Log output

```
file:///Users/helder/Projects/dagger/sdk/nodejs/api/utils.ts:5
  GraphQLRequestError,
                                                                ^
GraphQLRequestError: API Error
    at file:///Users/helder/Projects/dagger/sdk/nodejs/api/utils.ts:203:13
    at Generator.throw (<anonymous>)
    at rejected (file:///Users/helder/Projects/dagger/sdk/nodejs/api/utils.ts:5:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  cause: ClientError: GraphQL Error (Code: 200): {"response":{"error":"{\"data\":{\"container\":{\"from\":{\"envVariable\":\"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"}}}}","status":200,"headers":{}},"request":{"query":"\n        { container  { from (address: \"alpine\") { envVariable (name: \"PATH\") }} }\n      "}}
      at makeRequest (file:///Users/helder/Projects/dagger/sdk/nodejs/node_modules/graphql-request/src/index.ts:426:11)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    response: {
      error: '{"data":{"container":{"from":{"envVariable":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"}}}}',
      status: 200,
      headers: [Headers]
    },
    request: {
      query: '\n' +
        '        { container  { from (address: "alpine") { envVariable (name: "PATH") }} }\n' +
        '      ',
      variables: undefined
    }
  },
  code: 'D100',
  requestContext: {
    query: '\n' +
      '        { container  { from (address: "alpine") { envVariable (name: "PATH") }} }\n' +
      '      ',
    variables: undefined
  },
  response: {
    error: '{"data":{"container":{"from":{"envVariable":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"}}}}',
    status: 200,
    headers: Headers { [Symbol(map)]: [Object: null prototype] }
  }
}
```

### Steps to reproduce

Same thing with label:

```ts
import Client, { connect } from "@dagger.io/dagger"

connect(async (client: Client) => {
  console.log(await client.container().from("nginx").label("maintainer"))
})
```
Response looks ok, but it's being raised as a `ClientError`:
```js
  code: 'D100',
  requestContext: {
    query: '\n' +
      '        { container  { from (address: "nginx") { label (name: "maintainer") }} }\n' +
      '      ',
    variables: undefined
  },
  response: {
    error: '{"data":{"container":{"from":{"label":"NGINX Docker Maintainers \\u003cdocker-maint@nginx.com\\u003e"}}}}',
    status: 200,
    headers: Headers { [Symbol(map)]: [Object: null prototype] }
  }
```

### SDK version

Node.js SDK on main (9aff03b6150c1ab45189523a63f2a97f1ddac283)

### OS version

macOS 13.4.1

**Comment by helderco** [comment]
Encountered in https://github.com/dagger/dagger/issues/5449

**Comment by JammUtkarsh** [comment]
Is this issue fixed? I followed [NodeJS guide](https://docs.dagger.io/sdk/nodejs/783645/get-started) to setup my project, followed your **steps-to-reproduce** and the output is:
```bash
(node:40255) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

NGINX Docker Maintainers <docker-maint@nginx.com>
```

Am I missing something here?

**Project Structure:**
```bash
.
├── build.mts
├── node_modules
├── package-lock.json
├── package.json
└── tsconfig.json
```

**Comment by helderco** [comment]
You're right! I must have had a bad environment when I ran this. There's no issue, thanks. 🙏
