### ISSUE TITLE
🐞 dagger.exceptions.QueryError: lstat /tmp/buildkit-mount2680086245/meta/stdout: no such file or directory

### ISSUE THREAD

**Issue by jcrben** [dagger/dagger#5553]
### What is the issue?

I copied the code from https://docs.dagger.io/593914/quickstart-hello but I needed to run my own "runner" as I have a self-signed certificate. I used a combination of https://docs.dagger.io/1224/self-signed-certificates/# and https://github.com/dagger/dagger/blob/main/core/docs/d7yxc-operator_manual.md

```python
import sys

import anyio
import dagger


async def main():
    config = dagger.Config(log_output=sys.stdout)

    # initialize Dagger client
    async with dagger.Connection(config) as client:
        # use a python:3.11-slim container
        # get version
        python = (
            client.container().from_("python:3.11-slim").with_exec(["python", "-V"])
        )

        # execute
        version = await python.stdout()

    # print output
    print(f"Hello from Dagger and {version}")


anyio.run(main)
```

### Log output

(venv) ben@~/dagger-play/hello-dagger$ (main) python ci/main.py
3: resolve image config for docker.io/library/python:3.11-slim
3: > in from python:3.11-slim
3: resolve image config for docker.io/library/python:3.11-slim DONE

8: pull docker.io/library/python:3.11-slim
8: > in from python:3.11-slim
8: resolve docker.io/library/python:3.11-slim@sha256:36b544be6e796eb5caa0bf1ab75a17d2e20211cad7f66f04f6f5c9eeda930ef5
8: resolve docker.io/library/python:3.11-slim@sha256:36b544be6e796eb5caa0bf1ab75a17d2e20211cad7f66f04f6f5c9eeda930ef5 [0.02s]
8: pull docker.io/library/python:3.11-slim CACHED

6: exec python -V
6: [0.11s] Python 3.11.4
6: exec python -V DONE
Traceback (most recent call last):
  File "/home/ben/dagger-play/hello-dagger/venv/lib/python3.11/site-packages/dagger/api/base.py", line 244, in _handle_execute
    yield
  File "/home/ben/dagger-play/hello-dagger/venv/lib/python3.11/site-packages/dagger/api/base.py", line 157, in execute
    result = await self.session.execute(query)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ben/dagger-play/hello-dagger/venv/lib/python3.11/site-packages/gql/client.py", line 1231, in execute
    raise TransportQueryError(
gql.transport.exceptions.TransportQueryError: {'message': 'lstat /tmp/buildkit-mount2680086245/meta/stdout: no such file or directory', 'locations': [{'line': 5, 'column': 9}], 'path': ['container', 'from', 'withExec', 'stdout']}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ben/dagger-play/hello-dagger/ci/main.py", line 25, in <module>
    anyio.run(main)
  File "/home/ben/dagger-play/hello-dagger/venv/lib/python3.11/site-packages/anyio/_core/_eventloop.py", line 68, in run
    return asynclib.run(func, *args, **backend_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ben/dagger-play/hello-dagger/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 204, in run
    return native_run(wrapper(), debug=debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ben/.asdf/installs/python/3.11.4/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/ben/.asdf/installs/python/3.11.4/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ben/.asdf/installs/python/3.11.4/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ben/dagger-play/hello-dagger/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 199, in wrapper
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/home/ben/dagger-play/hello-dagger/ci/main.py", line 19, in main
    version = await python.stdout()
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ben/dagger-play/hello-dagger/venv/lib/python3.11/site-packages/dagger/api/base.py", line 486, in async_wrapper
    return await bear(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(dagger.api.gen.Container.stdout) at 0x7f464cbc6340>", line 10, in stdout
  File "/home/ben/dagger-play/hello-dagger/venv/lib/python3.11/site-packages/dagger/api/gen.py", line 878, in stdout
    return await _ctx.execute(str)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ben/dagger-play/hello-dagger/venv/lib/python3.11/site-packages/dagger/api/base.py", line 156, in execute
    with self._handle_execute(query):
  File "/home/ben/.asdf/installs/python/3.11.4/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ben/dagger-play/hello-dagger/venv/lib/python3.11/site-packages/dagger/api/base.py", line 270, in _handle_execute
    raise error from e
dagger.exceptions.QueryError: lstat /tmp/buildkit-mount2680086245/meta/stdout: no such file or directory

### Steps to reproduce

Code is precisely the code at https://docs.dagger.io/593914/quickstart-hello

1. docker pull moby/buildkit
2. docker run --net=host -d --restart always -v /usr/local/share/ca-certificates/ca-bundle-fixed.crt:/etc/ssl/certs/my-cert.pem -v dagger-engine:/var/lib/dagger --name dagger-buildkitd --privileged moby/buildkit:latest
3. export _EXPERIMENTAL_DAGGER_RUNNER_HOST=docker-container://dagger-buildkitd
4.  python ci/main.py

### SDK version

Python 0.6.4

### OS version

Windows 10 utilizing WSL2 - Ubuntu 20.04

**Comment by jcrben** [comment]
That worked, thanks! I ran this instead for step 3 above:
`docker run --net=host -d --restart always -v /usr/local/share/ca-certificates/ca-bundle-fixed.crt:/etc/ssl/certs/my-cert.pem -v dagger-engine:/var/lib/dagger --name dagger-buildkitd --privileged registry.dagger.io/engine:v0.6.4`
