### ISSUE TITLE
🐞 Interactive TUI seems broken since Dagger 0.8.x

### ISSUE THREAD

**Issue by ecattez** [dagger/dagger#5662]
### What is the issue?

I upgraded from Dagger 0.6 to Dagger 0.8. The experimental dagger interactive terminal UI is now broken. As a developer, this interface is really useful and I would like to keep it ;)

### Log output

```
Caught panic:

runtime error: invalid memory address or nil pointer dereference

Restoring terminal...

goroutine 8 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x1c
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.24.2/tea.go:440 +0x8c
panic({0x1015f6ba0, 0x1020161f0})
        /usr/local/go/src/runtime/panic.go:890 +0x258
github.com/dagger/dagger/internal/tui.(*Details).SetItem(...)
        /app/internal/tui/details.go:37
github.com/dagger/dagger/internal/tui.Model.processUpdate({0x140005a7b70, {0x10179f7e0, 0x1400002a780}, 0x1400002a840, 0x1400002a870, 0x1400002a8a0, 0x14000155900, {{0x0, 0x0}, 0xcb, ...}, ...}, ...)
        /app/internal/tui/model.go:302 +0x61c
github.com/dagger/dagger/internal/tui.Model.Update({0x140005a7b70, {0x10179f7e0, 0x1400002a780}, 0x1400002a840, 0x1400002a870, 0x1400002a8a0, 0x14000155900, {{0x1017b64e0, 0x14000118000}, 0xcb, ...}, ...}, ...)
        /app/internal/tui/model.go:138 +0x4c0
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0x140002dc180, {0x1017a7450?, 0x1400058ee00?}, 0x0?)
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.24.2/tea.go:373 +0x5d8
github.com/charmbracelet/bubbletea.(*Program).Run(0x140002dc180)
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.24.2/tea.go:503 +0x74c
main.interactiveTUI.func1()
        /app/cmd/dagger/engine.go:136 +0x28
created by main.interactiveTUI
        /app/cmd/dagger/engine.go:135 +0x1c8
```

### Steps to reproduce

```
env _EXPERIMENTAL_DAGGER_INTERACTIVE_TUI=1 dagger run ts-node --esm build.mjs
```

The content build.mjs is a "default" node setup with npm install and npm test. Pipeline is working fine without the env var.

### SDK version

@dagger.io/dagger 0.8.4

### OS version

macOS 13.2

**Comment by samalba** [comment]
I just hit the same issue with a Python pipeline:

```
$ dagger run ./dagger_pipeline.py
Caught panic:

runtime error: invalid memory address or nil pointer dereference

Restoring terminal...

goroutine 6 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x1c
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.24.2/tea.go:440 +0x8c
panic({0x1013a2ba0, 0x101dc21f0})
        /usr/local/go/src/runtime/panic.go:890 +0x258
github.com/dagger/dagger/internal/tui.(*Details).SetItem(...)
        /app/internal/tui/details.go:37
github.com/dagger/dagger/internal/tui.Model.Update({0x14000117d30, {0x10154b7e0, 0x140003ec690}, 0x140003ec750, 0x140003ec780, 0x140003ec7e0, 0x14000139900, {{0x0, 0x0}, 0x8c, ...}, ...}, ...)
        /app/internal/tui/model.go:134 +0xf4
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0x140003be240, {0x101553450?, 0x140000c4e00?}, 0x0?)
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.24.2/tea.go:373 +0x5d8
github.com/charmbracelet/bubbletea.(*Program).Run(0x140003be240)
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.24.2/tea.go:503 +0x74c
main.interactiveTUI.func1()
        /app/cmd/dagger/engine.go:136 +0x28
created by main.interactiveTUI
        /app/cmd/dagger/engine.go:135 +0x1c8
```

**Comment by vito** [comment]
Sorry about the breakage, will try to get to the bottom of this tomorrow! I added a `nil` check to the place that's panicking, but even with that the UI seems super borked, so there's something deeper going on.
