### ISSUE TITLE
🖐️ 502 bad gateway when running

### ISSUE THREAD

**Issue by from-nibly** [dagger/dagger#5856]
### What happened? What did you expect to happen?

# Context
After migrating our jobs to github enterprise cloud one of our builds stopped working. We're still running inside the same self hosted runner, but now they run in an amazon account instead of our onprem server. I have no idea if that has anything to do with it but just in case.

I'm using dagger 0.8.7 with the python SDK, running the python script without the dagger cli.

# Discussion
This error is what sticks out to me.

```
Server error '502 Bad Gateway' for url 'http://127.0.0.1:33571/query'
```
I assume dagger is trying to call itself during some step? I'm not sure what would cause this? maybe network latency? the 502 doesn't help give much detail here.

# logs
```
Publishing image miniconda3:23.5.2-0-1.0.0 [<dagger.Container object at 0x7fe2f7d0ea40>]
  + Exception Group Traceback (most recent call last):
  |   File "/runner/_work/docker-images/docker-images/./build.py", line 136, in <module>
  |     anyio.run(build)
  |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 66, in run
  |     return async_backend.run(func, args, {}, backend_options)
  |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1968, in run
  |     return native_run(wrapper(), debug=debug)
  |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/runners.py", line 44, in run
  |     return loop.run_until_complete(main)
  |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
  |     return future.result()
  |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1961, in wrapper
  |     return await func(*args)
  |   File "/runner/_work/docker-images/docker-images/./build.py", line 91, in build
  |     async with anyio.create_task_group() as tg:
  |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 664, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dagger/client/_transport/httpx.py", line 81, in _prepare_result
    |     result: Dict[str, Any] = response.json()
    |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/httpx/_models.py", line 756, in json
    |     return jsonlib.loads(self.text, **kwargs)
    |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/json/__init__.py", line 346, in loads
    |     return _default_decoder.decode(s)
    |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/json/decoder.py", line 337, in decode
    |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/json/decoder.py", line 355, in raw_decode
    |     raise JSONDecodeError("Expecting value", s, err.value) from None
    | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dagger/client/_transport/httpx.py", line 101, in _raise_response_error
    |     response.raise_for_status()
    |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/httpx/_models.py", line 749, in raise_for_status
    |     raise HTTPStatusError(message, request=request, response=self)
    | httpx.HTTPStatusError: Server error '502 Bad Gateway' for url 'http://127.0.0.1:33571/query'
    | For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502
    | 
    | The above exception was the direct cause of the following exception:
    | 
    | Traceback (most recent call last):
    |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dagger/client/_core.py", line 149, in execute
    |     result = await self.conn.session.execute(query)
    |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dagger/client/_session.py", line 126, in execute
    |     return await (await self.get_session()).execute(query)
    |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/gql/client.py", line 1220, in execute
    |     result = await self._execute(
    |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/gql/client.py", line 1410, in _execute
    |     return await self._execute_with_retries(
    |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/backoff/_async.py", line 151, in retry
    |     ret = await target(*args, **kwargs)
    |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/gql/client.py", line 1383, in _execute_once
    |     answer = await super()._execute(
    |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/gql/client.py", line 1126, in _execute
    |     result = await asyncio.wait_for(
    |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    |     return await fut
    |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dagger/client/_transport/httpx.py", line 181, in execute
    |     return self._prepare_result(response)
    |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dagger/client/_transport/httpx.py", line 84, in _prepare_result
    |     self._raise_response_error(response, "Not a JSON answer")
    |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dagger/client/_transport/httpx.py", line 103, in _raise_response_error
    |     raise TransportServerError(str(e), e.response.status_code) from e
    | gql.transport.exceptions.TransportServerError: Server error '502 Bad Gateway' for url 'http://127.0.0.1:33571/query'
    | For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502
    | 
    | The above exception was the direct cause of the following exception:
    | 
    | Traceback (most recent call last):
    |   File "/runner/_work/docker-images/docker-images/./build.py", line 124, in build_image
    |     await img.publish(
    |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dagger/client/_guards.py", line 129, in async_wrapper
    |     return await bear(*args, **kwargs)
    |   File "<@beartype(dagger.client.gen.Container.publish) at 0x7fe2fd7779a0>", line 101, in publish
    |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dagger/client/gen.py", line 735, in publish
    |     return await _ctx.execute(str)
    |   File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dagger/client/_core.py", line 170, in execute
    |     raise TransportError(msg) from e
    | dagger.TransportError: Unexpected response from engine: Server error '502 Bad Gateway' for url 'http://127.0.0.1:33571/query'
    | For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502
    +------------------------------------
```

**Comment by sipsma** [comment]
Agree the error here is not helpful. @helderco the codepaths where this could happen are [here](https://github.com/sipsma/dagger/blob/efeb21ffdf0ed9349dd79bf387632a217e436c06/engine/client/client.go#L537-L537) and [here](https://github.com/sipsma/dagger/blob/efeb21ffdf0ed9349dd79bf387632a217e436c06/engine/client/client.go#L565-L565). Is it possible that the Python SDK could also print the body when this happens, just so there's a little more context? I'm also not at all sure how the other SDKs behave in this exact scenario, may not be solvable in the Python SDK specifically, just an initial thought.

@from-nibly One thing to clarify, have you setup a custom dagger engine separately and then having your Python code connect to that via an `_EXPERIMENTAL_DAGGER_RUNNER_HOST` env var? Or are you just executing the Python code directly without any custom engine?
* If you don't know what I'm talking about, which is totally fine, then you are most likely following the default path of no custom engine 🙂

Depending on that, we can help debug further. Also, if the code you are running happens to be open source, a link to it and/or the setup code you use to run it could be helpful too.

**Comment by from-nibly** [comment]
I am not using a custom dagger buildkit engine just using the SDK raw.

My code is not open source but I can probably post the root build script. My script is like a docker mono repo build, it's just a bunch of company base images.

Feel free to gawk and point out ~idiotic~ less than ideal things I'm doing in the script (there are probably many, one of which I'm guessing is causing this nasty issue)

the idea is to initiate all the docker builds and just saturate the CPU and I/O as much as possible to try to keep things a little speedy (this thing runs a crudload of builds) at some point I'm going to look into deciding whether or not a build image is going to be new or not (or maybe caching stuff and sidestepping that problem).

```python
#!/usr/bin/env python
# ... imports
builders = [
   #... various images we are building
]

parser = argparse.ArgumentParser(description="Build Docker images")
parser.add_argument("-l", "--load", action="store_true")
parser.add_argument("-p", "--publish", action="store_true")
parser.add_argument("-i", "--image", nargs="+", action="extend", dest="images")
parser.add_argument("-t", "--tag", nargs="+", action="extend", dest="tags")


default_variants = ["linux/amd64"]

def select_platform_variants(builder, args: Namespace) -> List[str]:
    variants = builder.variants or default_variants

    if len(variants) == 0:
        raise Exception(
            f"Variant selection {args.variants} results in 0 matching variants for image {builder.name}: {builder.variants} are available"
        )
    return variants

def shorten_variant(variant: str) -> str:
    return variant.split("/")[1]

async def build():
    args = parser.parse_args()

    async with dagger.Connection(dagger.Config(log_output=sys.stderr)) as client:
        for BuilderClass in builders:
            builder = BuilderClass(client)

            if (
                args.images is not None
                and len(args.images) > 0
                and not builder.name in args.images
            ):
                print(f"Skipping image not selected for build {builder.name}")
                continue

            images: Dict = defaultdict(list)

            variants = select_platform_variants(builder, args)

            for variant in variants:
                for tag in builder.tags:
                    if (
                        args.tags is not None
                        and len(args.tags) > 0
                        and not tag in args.tags
                    ):
                        continue

                    image = builder.image(tag, Platform(variant))
                    print(f"Building image with [tag: {tag}, variant: {variant}]")
                    images[tag].append({"image": image, "variant": variant})

            async with anyio.create_task_group() as tg:
                for tag, contexts in images.items():

                    async def build_image(builder, contexts, tag):
                        full_tag = f"{tag}-{builder.revision}"

                        if args.load:
                            path = f"/tmp/{builder.name}_{full_tag}.tar"

                            # Builds each platform variant as sep images because `docker load` does
                            # not support multi-platform images
                            for cntx in contexts:
                                await cntx.get("image").export(
                                    path, media_types=ImageMediaTypes.DockerMediaTypes
                                )

                                subprocess.run(
                                    [
                                        f"id=$(docker load --input {path} | "
                                        f"grep -o 'sha256.*' | "
                                        f"cut -f2- -d:) && "
                                        f"docker tag $id {builder.name}_{cntx.get('variant')}:{full_tag}"
                                    ],
                                    shell=True,
                                )

                        if args.publish:
                            img: Container = contexts[0].get("image")
                            # The remainder of the images are platform variants
                            rest = [c.get("image") for c in contexts[1:]]

                            print(f"Publishing image {builder.name}:{full_tag}", rest)
                            image_name = f"myrepo.example.com/{builder.name}:{full_tag}"
                            await img.publish(
                                image_name,
                                platform_variants=rest,
                                media_types=ImageMediaTypes.DockerMediaTypes,
                            )
                        for context in contexts:
                            await context.get("image").sync()

                    tg.start_soon(build_image, builder, contexts, tag)


if __name__ == "__main__":
    anyio.run(build)

```

**Comment by from-nibly** [comment]
Is there any more information I can provide that would help narrow down the issue?

**Comment by helderco** [comment]
The error shows that this is being triggered by the `img.publish` step. It's getting an unexpected response from your container registry.

**Comment by helderco** [comment]
The real error is `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)` from the response on publish. Request was made but response is unexpected. After that there's a cascading failure. May be EOF there.

**Comment by from-nibly** [comment]
Will check on Monday. That's definitely possible.

**Comment by from-nibly** [comment]
Yeah this was definitely some weird networking issue. We can close this though I think there's still a vague suggestion to see if there's a way to clean up the error output.
