### ISSUE TITLE
Zenith: error creating module named "Go"

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#5975]
```
~/G/g/F/P/go ❯❯❯ dagger mod init --name Go --sdk go                                                                                                         bugfix/prevent-stack-smashing ✱ ◼
✘ asModule(sourceSubpath: ".") ERROR [0.92s]
✘ .....
✘ generating go module: Go ERROR [0.09s]
├ [0.02s] go mod tidy
┃ writing dagger.gen.go
┃ writing go.mod
┃ writing go.sum
┃ writing main.go
┃ creating directory querybuilder
┃ writing querybuilder/marshal.go
┃ writing querybuilder/querybuilder.go
┃ panic: go: internal error: missing go root module
┃
┃ goroutine 1 [running]:
┃ cmd/go/internal/modload.mustHaveGoRoot(...)
┃         cmd/go/internal/modload/buildlist.go:104
┃ cmd/go/internal/modload.newRequirements(0xe0?, {0x4000218b40?, 0x543be0?, 0x40001720f0?}, 0x5aedc0?)
┃         cmd/go/internal/modload/buildlist.go:118 +0x584
┃ cmd/go/internal/modload.updateUnprunedRoots({0x71df30?, 0xab31e0?}, 0x0?, 0x40000f20a0, {0x0, 0x0, 0x3d0f40?})
┃         cmd/go/internal/modload/buildlist.go:1465 +0x820
┃ cmd/go/internal/modload.updateRoots({0x71df30?, 0xab31e0?}, 0x0?, 0x40000a80c0?, {0x0?, 0x2?, 0x40000a80c0?}, {0x0?, 0x0?, 0x40000a80d0?}, ...)
┃         cmd/go/internal/modload/buildlist.go:781 +0x6c
┃ cmd/go/internal/modload.loadModFile({0x71df30, 0xab31e0}, 0x40000fe280)
┃         cmd/go/internal/modload/init.go:939 +0x134c
┃ cmd/go/internal/modload.LoadPackages({0x71df30?, 0xab31e0}, {{0x0, 0x0}, 0x4000119ef0, 0x1, {0x0, 0x0}, 0x1, 0x1, ...}, ...)
┃         cmd/go/internal/modload/load.go:345 +0x31c
┃ cmd/go/internal/modcmd.runTidy({0x71df30, 0xab31e0}, 0x40000ea4c8?, {0x400009e1a0?, 0x54c8e0?, 0x10edbc?})
┃         cmd/go/internal/modcmd/tidy.go:127 +0x204
┃ main.invoke(0xa70ea0, {0x400009e1a0, 0x1, 0x1})
┃         cmd/go/main.go:268 +0x4f0
┃ main.main()
┃         cmd/go/main.go:186 +0x754
┃ needs another pass...
• Engine: c8919d4606c0 (version v0.9.1)
```

Not immediately sure why this would happen (other names like "Golang" are find); need to dig through stack trace.

**Comment by sipsma** [comment]
@vito pointed out that we name the go module in `go.mod` w/ the name of the dagger module, which causes this.

We're gonna just change to naming the go module `main`; users are free to modify this at any point after anyways so a boring default like `main` is safe.
