### ISSUE TITLE
🐞 Quickstart "Use caching" python source is missing exclusion

### ISSUE THREAD

**Issue by pythoninthegrass** [dagger/dagger#6212]
### What is the issue?

Running through the caching leg of the python quickstart as-is doesn't complete as expected. Line 24 is missing `exclude=` in front of `["node_modules/", "ci/"]`.

**Bug**
```python
source = (
            client.container()
            .from_("node:16-slim")
            .with_directory(
                "/src",
                client.host().directory("."),
                ["node_modules/", "ci/"],
            )
            .with_mounted_cache("/src/node_modules", node_cache)
        )
```

**Fix**
```python
source = (
            client.container()
            .from_(node_image)
            .with_directory(
                "/src",
                client.host().directory("."),
                exclude=["node_modules/", "ci/"]
            )
            .with_mounted_cache("/src/node_modules", node_cache)
        )
```

### Log output

```
λ dagger run python ci/cache.py
┣─╮
│ ▽ init
│ █ [1.00s] connect
│ ┣ [0.77s] starting engine
│ ┣ [0.22s] starting session
│ ┃ OK!
│ ┻
█ [0.64s] ERROR python ci/cache.py
┃ Traceback (most recent call last):
┃   File "/Users/lance.stephens/git/hello-dagger/ci/cache.py", line 53, in <module>
┃     anyio.run(main)
┃   File "/Users/lance.stephens/git/hello-dagger/ci/.venv/lib/python3.11/site-packages/anyio/_core/_eventloop.py", line 66, in run
┃     return async_backend.run(func, args, {}, backend_options)
┃            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
┃   File "/Users/lance.stephens/git/hello-dagger/ci/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1960, in run
┃     return native_run(wrapper(), debug=debug)
┃            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
┃   File "/Users/lance.stephens/.asdf/installs/python/3.11.6/lib/python3.11/asyncio/runners.py", line 190, in run
┃     return runner.run(main)
┃            ^^^^^^^^^^^^^^^^
┃   File "/Users/lance.stephens/.asdf/installs/python/3.11.6/lib/python3.11/asyncio/runners.py", line 118, in run
┃     return self._loop.run_until_complete(task)
┃            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
┃   File "/Users/lance.stephens/.asdf/installs/python/3.11.6/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
┃     return future.result()
┃            ^^^^^^^^^^^^^^^
┃   File "/Users/lance.stephens/git/hello-dagger/ci/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1953, in wrapper
┃     return await func(*args)
┃            ^^^^^^^^^^^^^^^^^
┃   File "/Users/lance.stephens/git/hello-dagger/ci/cache.py", line 22, in main
┃     .with_directory("/src",
┃      ^^^^^^^^^^^^^^^^^^^^^^
┃   File "/Users/lance.stephens/git/hello-dagger/ci/.venv/lib/python3.11/site-packages/dagger/client/_guards.py", line 138, in wrapper
┃     return bear(*args, **kwargs)
┃            ^^^^^^^^^^^^^^^^^^^^^
┃   File "<@beartype(dagger.client.gen.Container.with_directory) at 0x106424720>", line 127, in with_directory
┃ TypeError: Container.with_directory() takes 3 positional arguments but 4 were given
┻
• Engine: fd4303b34f2d (version v0.9.3)
⧗ 1.64s ✔ 4 ✘ 1
exit status 1
```

### Steps to reproduce

Run the [code](https://docs.dagger.io/quickstart/635927/caching) as-is:
```python
import random
import sys

import anyio
import dagger

async def main():
    config = dagger.Config(log_output=sys.stdout)

    async with dagger.Connection(config) as client:
        # create a cache volume
        node_cache = client.cache_volume("node")

        # use a node:16-slim container
        # mount the source code directory on the host
        # at /src in the container
        # mount the cache volume to persist dependencies
        source = (
            client.container()
            .from_("node:16-slim")
            .with_directory(
                "/src",
                client.host().directory("."),
                ["node_modules/", "ci/"],
            )
            .with_mounted_cache("/src/node_modules", node_cache)
        )

        # set the working directory in the container
        # install application dependencies
        runner = source.with_workdir("/src").with_exec(["npm", "install"])

        # run application tests
        test = runner.with_exec(["npm", "test", "--", "--watchAll=false"])

        # first stage
        # build application
        build_dir = test.with_exec(["npm", "run", "build"]).directory("./build")

        # second stage
        # use an nginx:alpine container
        # copy the build/ directory from the first stage
        # publish the resulting container to a registry
        image_ref = await (
            client.container()
            .from_("nginx:1.23-alpine")
            .with_directory("/usr/share/nginx/html", build_dir)
            .publish(f"ttl.sh/hello-dagger-{random.randint(0, 10000000)}")
        )

    print(f"Published image to: {image_ref}")


anyio.run(main)
```
via `dagger run python ci/main.py`

### SDK version

Python SDK 0.9.3

### OS version

macOS 12.5 (21G72)

**Comment by helderco** [comment]
Thanks for reporting! 

@vikram-dagger, must be an invalid cache in the web server as the referenced embed is correct:

https://github.com/dagger/dagger/blob/3bdef92b1ab0df8a81248ceebe1fcf47b09c805e/docs/current/quickstart/635927-caching.mdx#L18

✅ https://docs.dagger.io/embed/TCdOYrKMfV_d

What you see in the web page is a different one

<img width="606" alt="Screenshot 2023-12-04 at 18 04 01" src="https://github.com/dagger/dagger/assets/174525/3223c642-d0c2-41ed-9d81-6f146f028d59">

❌ https://docs.dagger.io/embed/sNZQEeULT-M

**Comment by vikram-dagger** [comment]
I've redeployed the docs with a clean cache and the page now has the correct code:

![image](https://github.com/dagger/dagger/assets/112123850/5adc272c-bd57-460a-8f5b-e6c18b9a2fee)
