### ISSUE TITLE
🐞 sdk(elixir): wrong os type and architecture detection on Windows for cli downloader

### ISSUE THREAD

**Issue by cubeee** [dagger/dagger#6540]
### What is the issue?

Elixir SDK CLI downloader's `:os.type()` pattern matching expects `{:windows, :nt}` but is actually `{:win32, :nt}` [as documented in Erlang](https://www.erlang.org/doc/man/os#type-0).

[https://github.com/dagger/dagger/blob/7350f0b8dd5ff74b7ae0ddfd05e35c37bf16712b/sdk/elixir/lib/dagger/internal/engine/downloader.ex#L120-L126](https://github.com/dagger/dagger/blob/7350f0b8dd5ff74b7ae0ddfd05e35c37bf16712b/sdk/elixir/lib/dagger/internal/engine/downloader.ex#L120-L126)

```
Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.16.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :os.type()
{:win32, :nt}
```

After that, a correct system architecture can't be matched.
[https://github.com/dagger/dagger/blob/7350f0b8dd5ff74b7ae0ddfd05e35c37bf16712b/sdk/elixir/lib/dagger/internal/engine/downloader.ex#L113-L118](https://github.com/dagger/dagger/blob/7350f0b8dd5ff74b7ae0ddfd05e35c37bf16712b/sdk/elixir/lib/dagger/internal/engine/downloader.ex#L113-L118)

```
Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.16.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :erlang.system_info(:system_architecture) |> to_string()
"win32"
```

### Dagger version

Elixir SDK 0.9.7

### Steps to reproduce

Run on Windows without a previously downloaded CLI

```elixir
Mix.install([
  {:dagger, "~> 0.9", only: [:dev, :test]}
])
 
Dagger.connect!()
  |> Dagger.Client.container()
  |> Dagger.Container.from("bash:latest")
  |> Dagger.Container.with_entrypoint('')
  |> Dagger.Container.with_exec(~w"echo 'hello'")
  |> Dagger.Sync.sync()
 
```

### Log output

os type:

```
** (CaseClauseError) no case clause matching: {:win32, :nt}
    (dagger 0.9.7) lib/dagger/internal/engine/downloader.ex:121: Dagger.Internal.Engine.Downloader.os/0
    (dagger 0.9.7) lib/dagger/internal/engine/downloader.ex:11: Dagger.Internal.Engine.Downloader.download/2
    (dagger 0.9.7) lib/dagger/engine_conn.ex:59: Dagger.EngineConn.from_remote_cli/1
    (dagger 0.9.7) lib/dagger.ex:18: Dagger.connect/1
    (dagger 0.9.7) lib/dagger.ex:37: Dagger.connect!/1
    dagger_repro.ex:7: (file)
```

system architecture:

```
** (CaseClauseError) no case clause matching: "win32"
    (dagger 0.0.0) lib/dagger/internal/engine/downloader.ex:114: Dagger.Internal.Engine.Downloader.arch/0
    (dagger 0.0.0) lib/dagger/internal/engine/downloader.ex:109: Dagger.Internal.Engine.Downloader.cli_archive_url/2
    (dagger 0.0.0) lib/dagger/internal/engine/downloader.ex:30: Dagger.Internal.Engine.Downloader.extract_cli/3
    (dagger 0.0.0) lib/dagger/internal/engine/downloader.ex:19: Dagger.Internal.Engine.Downloader.download/2
    (dagger 0.0.0) lib/dagger/engine_conn.ex:60: Dagger.EngineConn.from_remote_cli/1
    (dagger 0.0.0) lib/dagger/internal/client.ex:13: Dagger.Internal.Client.connect/1
    (dagger 0.0.0) lib/dagger.ex:18: Dagger.connect/1
    (dagger 0.0.0) lib/dagger.ex:37: Dagger.connect!/1
```

**Comment by wingyplus** [comment]
Thank you for the report! Let me submit a fix tomorrow. 🙂
