### ISSUE TITLE
🐞 `dagger init` returns internal server erroro when inititate with git sdk

### ISSUE THREAD

**Issue by wingyplus** [dagger/dagger#6689]
### What is the issue?

Found on the PR https://github.com/dagger/dagger/pull/6559 which is already rebased on main. When create a module with git repository SDK (not a builtin). The engine returns internal server error instead of error from the SDK 

### Dagger version

dagger 4b825dc642cb6eb9a060e54bf8d69288fbee4904 (registry.dagger.io/engine) darwin/arm64

### Steps to reproduce

```
$ mkdir first-module
$ cd first-module
$ ~/src/github.com/dagger/dagger/hack/with-dev dagger init --sdk=github.com/wingyplus/daggerverse/elixir-sdk@main --name=first-module --debug
```

### Log output

The output log

```
✔ defaultPlatform: Platform! 0.0s
✔ moduleSource(refString: "."): ModuleSource! 0.0s
✔ ModuleSource.kind: ModuleSourceKind! 0.0s
✔ ModuleSource.resolveContextPathFromCaller: String! 0.0s
✔ ModuleSource.withName(name: "first-module"): ModuleSource! 0.0s
✔ ModuleSource.withSDK(sdk: "github.com/wingyplus/daggerverse/elixir-sdk@main"): ModuleSource! 0.0s
✔ ModuleSource.withSourceSubpath(path: "dagger"): ModuleSource! 0.0s
● ModuleSource.resolveFromCaller: ModuleSource! 1.8s
  ✔ moduleSource(refString: "github.com/wingyplus/daggerverse/elixir-sdk@main"): ModuleSource! 1.8s
    ✔ git(url: "https://github.com/wingyplus/daggerverse"): GitRepository! 0.0s
    ✔ GitRepository.commit(id: "main"): GitRef! 0.0s
    ✔ git://github.com/wingyplus/daggerverse#main 1.8s
    ┃ 6c0f03e6f07437b882a813a105a813f01bf2fd59        refs/heads/main                                                                                                           ✔ GitRef.tree: Directory! 0.0s

Error: failed to generate code: returned error 422 Unprocessable Entity: {"errors":[{"message":"internal system error"}],"data":null}
```

In the engine log

```
panic: panic: panic: panic: panic: runtime error: invalid memory address or nil pointer dereference
stacktrace:
goroutine 213167 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/sourcegraph/conc/panics.NewRecovered(0x199?, {0x160f260, 0x2b3cf80})
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/panics/panics.go:59 +0x70
github.com/sourcegraph/conc/panics.(*Catcher).tryRecover(0x40011f3c30)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/panics/panics.go:28 +0x58
panic({0x160f260?, 0x2b3cf80?})
        /usr/local/go/src/runtime/panic.go:914 +0x218
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:83
github.com/dagger/dagger/dagql.Class[...].Field(0x171ba0?, {0x19b91aa?, 0x1958800?})
        /app/dagql/objects.go:81 +0x50
github.com/dagger/dagger/dagql.Instance[...].IDFor(0x1d0b0a0, {0x18d5160?, 0xc0b4bc?}, {{0x19b91aa?, 0x11?}, {0x4001b1de60?, 0x1?, 0x1?}, 0x0?})
        /app/dagql/objects.go:254 +0x78
github.com/dagger/dagger/dagql.(*Server).cachedSelect(0x400161f680, {0x1cf1538, 0x400076ec90}, {0x1cf3998, 0x4001a62440}, {{0x19b91aa, 0x11}, {0x4001b1de60, 0x1, 0x1}, ...})
        /app/dagql/server.go:564 +0x74
github.com/dagger/dagger/dagql.(*Server).Select(0x1902200?, {0x1cf1538, 0x400076ec90}, {0x1cf3998?, 0x4001a62440}, {0x17efac0, 0x4001a62400}, {0x4001710298, 0x3, 0x20?})
        /app/dagql/server.go:465 +0xf0
github.com/dagger/dagger/core/schema.(*moduleSchema).sdkForModule(0x400188c288, {0x1cf1538, 0x400076ec90}, 0x40004ecb50?, {0x40000fe04d, 0x30}, {0x0, 0x0, {0x0, 0x0, ...}, ...})
        /app/core/schema/sdk.go:53 +0x358
github.com/dagger/dagger/core/schema.(*moduleSchema).collectCallerLocalDeps.func1({0x1cf1538, 0x400076ec90})
        /app/core/schema/modulesource.go:1015 +0x838
github.com/dagger/dagger/dagql.(*cacheMap[...]).GetOrInitializeOnHit(0x1d17ac0, {0x1cf1538, 0x4000882a50}, {0x400054fbd0, 0x43}, 0x4001c75020, 0x4001974818)
        /app/dagql/cachemap.go:85 +0x2b8
github.com/dagger/dagger/dagql.(*cacheMap[...]).GetOrInitialize(0x0?, {0x1cf1538?, 0x4000882a50?}, {0x400054fbd0?, 0x18b5dc0?}, 0x400076eb01?)
        /app/dagql/cachemap.go:60 +0x44
github.com/dagger/dagger/core/schema.(*moduleSchema).collectCallerLocalDeps(0x400188c288, {0x1cf1538, 0x4000882a50}, 0x40000d4c30, {0x400054fbd0, 0x36}, {0x400054fbd0, 0x43}, 0x1, 0x4001220780, ...)
        /app/core/schema/modulesource.go:886 +0x14c
github.com/dagger/dagger/core/schema.(*moduleSchema).moduleSourceResolveFromCaller(0x400188c288, {0x1cf1538, 0x4000882a50}, 0x4001220780, {})
        /app/core/schema/modulesource.go:643 +0x168
github.com/dagger/dagger/dagql.Func[...].func1({0x4001220100?, 0x4001220780?, {0x0, 0x1, 0x4001ba1a10, 0x4000bf2d88}, 0x0}, {})
        /app/dagql/objects.go:320 +0x60
github.com/dagger/dagger/dagql.NodeFunc[...].func1({0x4001220100, 0x4001220780, {0x0, 0x1, 0x4001ba1a10, 0x4000bf2d88}, 0x0}, 0xbfd6c0)
        /app/dagql/objects.go:355 +0xb4
github.com/dagger/dagger/dagql.Class[...].Call(0x1d1a1c0?, {0x1cf1538?, 0x4000882a50?}, {0x4001220100?, 0x4001220780, {0x0, 0x1, 0x4001ba1a10, 0x4000bf2d88}, 0x0}, ...)
        /app/dagql/objects.go:202 +0x114
github.com/dagger/dagger/dagql.Instance[...].Select(0x1d0b0a0, {0x1cf1538, 0x4000882a50}, {{0x40000fe0a1, 0x11}, {0x2ba63e0, 0x0, 0x0}, 0x0})
        /app/dagql/objects.go:271 +0x24c
github.com/dagger/dagger/dagql.(*Server).cachedSelect.func1({0x1cf1538?, 0x4000882a50?})
        /app/dagql/server.go:574 +0x54
github.com/dagger/dagger/tracing.AroundFunc.ProgrockAroundFunc.func1({0x1cf1538, 0x40008827e0})
        /app/tracing/graphql.go:101 +0x32c
github.com/dagger/dagger/tracing.AroundFunc.SpanAroundFunc.func2({0x1cf1538, 0x4000882390})
        /app/tracing/graphql.go:33 +0xa0
github.com/dagger/dagger/dagql.(*Server).cachedSelect(0x400161f680, {0x1cf1538, 0x40005fc120}, {0x1cf3998, 0x4000644540}, {{0x40000fe0a1, 0x11}, {0x2ba63e0, 0x0, 0x0}, ...})
        /app/dagql/server.go:581 +0x188
github.com/dagger/dagger/dagql.(*Server).resolvePath(0x40016e55e8?, {0x1cf1538, 0x40005fc120}, {0x1cf3998?, 0x4000644540?}, {{0x40000fe0a1, 0x11}, {{0x40000fe0a1, 0x11}, {0x2ba63e0, ...}, ...}, ...})
        /app/dagql/server.go:592 +0x7c
github.com/dagger/dagger/dagql.(*Server).Resolve.func1()
        /app/dagql/server.go:400 +0x78
github.com/dagger/dagger/dagql.(*Server).Resolve.(*ErrorPool).Go.func3()
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/pool/error_pool.go:30 +0x2c
github.com/sourcegraph/conc/pool.(*Pool).worker(0x40018cd918?)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/pool/pool.go:154 +0x68
github.com/sourcegraph/conc/panics.(*Catcher).Try(0x0?, 0x19?)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/panics/panics.go:23 +0x50
github.com/sourcegraph/conc.(*WaitGroup).Go.func1()
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/waitgroup.go:32 +0x58
created by github.com/sourcegraph/conc.(*WaitGroup).Go in goroutine 213166
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/waitgroup.go:30 +0x7c


stacktrace:
goroutine 213166 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/sourcegraph/conc/panics.NewRecovered(0x4001ded958?, {0x16773e0, 0x4001a62480})
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/panics/panics.go:59 +0x70
github.com/sourcegraph/conc/panics.(*Catcher).tryRecover(0x40011f39f0)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/panics/panics.go:28 +0x58
panic({0x16773e0?, 0x4001a62480?})
        /usr/local/go/src/runtime/panic.go:914 +0x218
github.com/sourcegraph/conc/panics.(*Catcher).Repanic(...)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/panics/panics.go:38
github.com/sourcegraph/conc.(*WaitGroup).Wait(0x40011f3c20)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/waitgroup.go:42 +0x5c
github.com/sourcegraph/conc/pool.(*Pool).Wait(0x40011f3c20)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/pool/pool.go:79 +0x34
github.com/sourcegraph/conc/pool.(*ErrorPool).Wait(...)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/pool/error_pool.go:37
github.com/dagger/dagger/dagql.(*Server).Resolve(0x400161f680, {0x1cf1538?, 0x40005fc120}, {0x1cf3998?, 0x4000644540}, {0x40011f3020, 0x1, 0x4000e9dcc0?})
        /app/dagql/server.go:408 +0x244
github.com/dagger/dagger/dagql.(*Server).resolvePath(0x40016e55e8?, {0x1cf1538, 0x40005fc120}, {0x1cf3998?, 0x4001ad38c0?}, {{0x40000fe080, 0x11}, {{0x40000fe080, 0x11}, {0x4000e9dcc0, ...}, ...}, ...})
        /app/dagql/server.go:650 +0x17c
github.com/dagger/dagger/dagql.(*Server).Resolve.func1()
        /app/dagql/server.go:400 +0x78
github.com/dagger/dagger/dagql.(*Server).Resolve.(*ErrorPool).Go.func3()
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/pool/error_pool.go:30 +0x2c
github.com/sourcegraph/conc/pool.(*Pool).worker(0x40018cd918?)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/pool/pool.go:154 +0x68
github.com/sourcegraph/conc/panics.(*Catcher).Try(0x0?, 0x19?)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/panics/panics.go:23 +0x50
github.com/sourcegraph/conc.(*WaitGroup).Go.func1()
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/waitgroup.go:32 +0x58
created by github.com/sourcegraph/conc.(*WaitGroup).Go in goroutine 213165
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/waitgroup.go:30 +0x7c


stacktrace:
goroutine 213165 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/sourcegraph/conc/panics.NewRecovered(0x40009eb958?, {0x16773e0, 0x4001a624c0})
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/panics/panics.go:59 +0x70
github.com/sourcegraph/conc/panics.(*Catcher).tryRecover(0x40011f34b0)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/panics/panics.go:28 +0x58
panic({0x16773e0?, 0x4001a624c0?})
        /usr/local/go/src/runtime/panic.go:914 +0x218
github.com/sourcegraph/conc/panics.(*Catcher).Repanic(...)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/panics/panics.go:38
github.com/sourcegraph/conc.(*WaitGroup).Wait(0x40011f39e0)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/waitgroup.go:42 +0x5c
github.com/sourcegraph/conc/pool.(*Pool).Wait(0x40011f39e0)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/pool/pool.go:79 +0x34
github.com/sourcegraph/conc/pool.(*ErrorPool).Wait(...)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/pool/error_pool.go:37
github.com/dagger/dagger/dagql.(*Server).Resolve(0x400161f680, {0x1cf1538?, 0x40005fc120}, {0x1cf3998?, 0x4001ad38c0}, {0x40011f3080, 0x1, 0x4000e9dca0?})
        /app/dagql/server.go:408 +0x244
github.com/dagger/dagger/dagql.(*Server).resolvePath(0x40016e55e8?, {0x1cf1538, 0x40005fc120}, {0x1cf3998?, 0x4001ad3040?}, {{0x40000fe040, 0x7}, {{0x40000fe040, 0x7}, {0x4000e9dca0, ...}, ...}, ...})
        /app/dagql/server.go:650 +0x17c
github.com/dagger/dagger/dagql.(*Server).Resolve.func1()
        /app/dagql/server.go:400 +0x78
github.com/dagger/dagger/dagql.(*Server).Resolve.(*ErrorPool).Go.func3()
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/pool/error_pool.go:30 +0x2c
github.com/sourcegraph/conc/pool.(*Pool).worker(0x40018cd918?)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/pool/pool.go:154 +0x68
github.com/sourcegraph/conc/panics.(*Catcher).Try(0x0?, 0x19?)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/panics/panics.go:23 +0x50
github.com/sourcegraph/conc.(*WaitGroup).Go.func1()
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/waitgroup.go:32 +0x58
created by github.com/sourcegraph/conc.(*WaitGroup).Go in goroutine 213164
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/waitgroup.go:30 +0x7c


stacktrace:
goroutine 213164 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/sourcegraph/conc/panics.NewRecovered(0x4000fbd958?, {0x16773e0, 0x4001a62500})
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/panics/panics.go:59 +0x70
github.com/sourcegraph/conc/panics.(*Catcher).tryRecover(0x40011f3270)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/panics/panics.go:28 +0x58
panic({0x16773e0?, 0x4001a62500?})
        /usr/local/go/src/runtime/panic.go:914 +0x218
github.com/sourcegraph/conc/panics.(*Catcher).Repanic(...)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/panics/panics.go:38
github.com/sourcegraph/conc.(*WaitGroup).Wait(0x40011f34a0)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/waitgroup.go:42 +0x5c
github.com/sourcegraph/conc/pool.(*Pool).Wait(0x40011f34a0)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/pool/pool.go:79 +0x34
github.com/sourcegraph/conc/pool.(*ErrorPool).Wait(...)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/pool/error_pool.go:37
github.com/dagger/dagger/dagql.(*Server).Resolve(0x400161f680, {0x1cf1538?, 0x40005fc120}, {0x1cf3998?, 0x4001ad3040}, {0x40011f30e0, 0x1, 0x4000e9dc80?})
        /app/dagql/server.go:408 +0x244
github.com/dagger/dagger/dagql.(*Server).resolvePath(0x40016e55e8?, {0x1cf1538, 0x40005fc120}, {0x1cf3998?, 0x4001ad2980?}, {{0x40000fe022, 0x8}, {{0x40000fe022, 0x8}, {0x4000e9dc80, ...}, ...}, ...})
        /app/dagql/server.go:650 +0x17c
github.com/dagger/dagger/dagql.(*Server).Resolve.func1()
        /app/dagql/server.go:400 +0x78
github.com/dagger/dagger/dagql.(*Server).Resolve.(*ErrorPool).Go.func3()
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/pool/error_pool.go:30 +0x2c
github.com/sourcegraph/conc/pool.(*Pool).worker(0x40018cd918?)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/pool/pool.go:154 +0x68
github.com/sourcegraph/conc/panics.(*Catcher).Try(0x0?, 0x19?)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/panics/panics.go:23 +0x50
github.com/sourcegraph/conc.(*WaitGroup).Go.func1()
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/waitgroup.go:32 +0x58
created by github.com/sourcegraph/conc.(*WaitGroup).Go in goroutine 213163
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/waitgroup.go:30 +0x7c


stacktrace:
goroutine 213163 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/sourcegraph/conc/panics.NewRecovered(0x4000e53958?, {0x16773e0, 0x4001a62540})
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/panics/panics.go:59 +0x70
github.com/sourcegraph/conc/panics.(*Catcher).tryRecover(0x40011f3210)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/panics/panics.go:28 +0x58
panic({0x16773e0?, 0x4001a62540?})
        /usr/local/go/src/runtime/panic.go:914 +0x218
github.com/sourcegraph/conc/panics.(*Catcher).Repanic(...)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/panics/panics.go:38
github.com/sourcegraph/conc.(*WaitGroup).Wait(0x40011f3260)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/waitgroup.go:42 +0x5c
github.com/sourcegraph/conc/pool.(*Pool).Wait(0x40011f3260)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/pool/pool.go:79 +0x34
github.com/sourcegraph/conc/pool.(*ErrorPool).Wait(...)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/pool/error_pool.go:37
github.com/dagger/dagger/dagql.(*Server).Resolve(0x400161f680, {0x1cf1538?, 0x40005fc120}, {0x1cf3998?, 0x4001ad2980}, {0x40011f3140, 0x1, 0x4000e9dc60?})
        /app/dagql/server.go:408 +0x244
github.com/dagger/dagger/dagql.(*Server).resolvePath(0x40016e55e8?, {0x1cf1538, 0x40005fc120}, {0x1cf4820?, 0x400036c200?}, {{0x40000fe006, 0xc}, {{0x40000fe006, 0xc}, {0x4000e9dc60, ...}, ...}, ...})
        /app/dagql/server.go:650 +0x17c
github.com/dagger/dagger/dagql.(*Server).Resolve.func1()
        /app/dagql/server.go:400 +0x78
github.com/dagger/dagger/dagql.(*Server).Resolve.(*ErrorPool).Go.func3()
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/pool/error_pool.go:30 +0x2c
github.com/sourcegraph/conc/pool.(*Pool).worker(0x40018cd918?)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/pool/pool.go:154 +0x68
github.com/sourcegraph/conc/panics.(*Catcher).Try(0x0?, 0x19?)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/panics/panics.go:23 +0x50
github.com/sourcegraph/conc.(*WaitGroup).Go.func1()
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/waitgroup.go:32 +0x58
created by github.com/sourcegraph/conc.(*WaitGroup).Go in goroutine 213159
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/waitgroup.go:30 +0x7c



goroutine 213159 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x1c
github.com/99designs/gqlgen/graphql.DefaultRecover({0x4001704e88?, 0x1f058?}, {0x16773e0?, 0x4001a62580?})
        /go/pkg/mod/github.com/99designs/gqlgen@v0.17.41/graphql/recovery.go:17 +0x70
github.com/99designs/gqlgen/graphql/executor.(*Executor).PresentRecoveredError(0x4000982fa0, {0x1cf1538, 0x4000174960}, {0x16773e0?, 0x4001a62580?})
        /go/pkg/mod/github.com/99designs/gqlgen@v0.17.41/graphql/executor/executor.go:157 +0x48
github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP.func1()
        /go/pkg/mod/github.com/99designs/gqlgen@v0.17.41/graphql/handler/server.go:105 +0x94
panic({0x16773e0?, 0x4001a62580?})
        /usr/local/go/src/runtime/panic.go:914 +0x218
github.com/sourcegraph/conc/panics.(*Catcher).Repanic(...)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/panics/panics.go:38
github.com/sourcegraph/conc.(*WaitGroup).Wait(0x40011f3200)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/waitgroup.go:42 +0x5c
github.com/sourcegraph/conc/pool.(*Pool).Wait(0x40011f3200)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/pool/pool.go:79 +0x34
github.com/sourcegraph/conc/pool.(*ErrorPool).Wait(...)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/pool/error_pool.go:37
github.com/dagger/dagger/dagql.(*Server).Resolve(0x400161f680, {0x1cf1538?, 0x40005fc120}, {0x1cf4820?, 0x400036c200}, {0x40011f31a0, 0x1, 0x277d0?})
        /app/dagql/server.go:408 +0x244
github.com/dagger/dagger/dagql.(*Server).ExecOp(0x400161f680, {0x1cf1538, 0x40005fc120}, 0x4000f97200)
        /app/dagql/server.go:374 +0x260
github.com/dagger/dagger/dagql.(*Server).Exec.func1({0x1cf1538, 0x40005fc120})
        /app/dagql/server.go:327 +0x13c
github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1.1({0x1cf1538, 0x40005fc120})
        /go/pkg/mod/github.com/99designs/gqlgen@v0.17.41/graphql/executor/executor.go:120 +0x2c
github.com/99designs/gqlgen/graphql/executor.processExtensions.func2({0x1cf1538?, 0x40005fc120?}, 0x1529d00?)
        /go/pkg/mod/github.com/99designs/gqlgen@v0.17.41/graphql/executor/extensions.go:66 +0x2c
github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1({0x1cf1538, 0x40005fc060})
        /go/pkg/mod/github.com/99designs/gqlgen@v0.17.41/graphql/executor/executor.go:119 +0x108
github.com/99designs/gqlgen/graphql/handler/transport.POST.Do({0x1cf1538?}, {0x1cea890?, 0x40011b1a40}, 0x40001e9300, {0x1cef900, 0x4000982fa0})
        /go/pkg/mod/github.com/99designs/gqlgen@v0.17.41/graphql/handler/transport/http_post.go:91 +0x45c
github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP(0x40019ffa40, {0x1cea890, 0x40011b1a40}, 0x40001e9300)
        /go/pkg/mod/github.com/99designs/gqlgen@v0.17.41/graphql/handler/server.go:122 +0x1fc
net/http.(*ServeMux).ServeHTTP(0xffff6ca099e8?, {0x1cea890, 0x40011b1a40}, 0x40001e9100)
        /usr/local/go/src/net/http/server.go:2514 +0x144
github.com/dagger/dagger/core/schema.(*APIServer).ServeHTTP.(*APIServer).ServeHTTP.flushAfterNBytes.func4.func5({0x1ce74b0?, 0x4001390460}, 0x4000e53901?)
        /app/core/schema/flusher.go:41 +0x1bc
net/http.HandlerFunc.ServeHTTP(0x4001225c00?, {0x1ce74b0?, 0x4001390460?}, 0x1cce760?)
        /usr/local/go/src/net/http/server.go:2136 +0x38
github.com/dagger/dagger/core/schema.(*APIServer).ServeHTTP(0x4001b0c3a8, {0x1ce74b0, 0x4001390460}, 0x4001041e00)
        /app/core/schema/schema.go:166 +0x37c
github.com/dagger/dagger/engine/server.(*DaggerServer).ServeClientConn.(*DaggerServer).HTTPHandlerForClient.func4({0x1ce74b0, 0x4001390460}, 0x4000d88a60?)
        /app/engine/server/server.go:197 +0x204
net/http.HandlerFunc.ServeHTTP(0x10?, {0x1ce74b0?, 0x4001390460?}, 0x4001390460?)
        /usr/local/go/src/net/http/server.go:2136 +0x38
net/http.serverHandler.ServeHTTP({0x1cda458?}, {0x1ce74b0?, 0x4001390460?}, 0x6?)
        /usr/local/go/src/net/http/server.go:2938 +0xbc
net/http.(*conn).serve(0x4000827680, {0x1cf1538, 0x40006dfda0})
        /usr/local/go/src/net/http/server.go:2009 +0x518
created by net/http.(*Server).Serve in goroutine 213155
        /usr/local/go/src/net/http/server.go:3086 +0x4cc
```

**Comment by wingyplus** [comment]
I think it's the same in the discussion in Discord https://discord.com/channels/707636530424053791/1120503349599543376/1206943715655032842.
