### ISSUE TITLE
🐞 Docs terminal command (on container output) not working as expected (MacOS M2)

### ISSUE THREAD

**Issue by lopezm94** [dagger/dagger#6853]
### What is the issue?

I'm following the [steps](https://docs.dagger.io/quickstart/883939/containers#start-an-interactive-terminal-session-with-the-container) described in the docs for chaining a terminall command to a container output and the following error appears.

```shell
> dagger call -m github.com/shykes/daggerverse/wolfi@v0.1.2 container --packages=cowsay terminal
✔ Wolfi.container(packages: ["cowsay"]): Container! 1.5s
  ✔ exec /runtime 1.5s
  ✔ Apko.wolfi(packages: ["cowsay"]): Container! 1.3s
    ✔ exec /runtime 1.3s
    ✔ Container.from(address: "cgr.dev/chainguard/apko"): Container! 0.9s
      ✔ resolve image config for cgr.dev/chainguard/apko:latest 0.9s
    ✔ Container.import(
        source: ✔ Container.file(path: "/layout.tar"): File! 0.0s
      ): Container! 0.1s

Error: response from query: input: container.import.terminal panic while resolving Container.terminal: runtime error: invalid memory address or nil pointer dereference

goroutine 672369 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/dagger/dagger/dagql.(*Server).resolvePath.func1()
        /app/dagql/server.go:642 +0x68
panic({0x160cdc0?, 0x2b3cfa0?})
        /usr/local/go/src/runtime/panic.go:914 +0x218
github.com/dagger/dagger/core/schema.(*containerSchema).terminal(0x1?, {0x1ce58f8, 0x40076179b0}, {0x40018a6700, 0x40007c1c00, {0x0, 0x1, 0x40035eb8c0, 0x4003bd0708}, 0x0}, ...)
        /app/core/schema/container.go:1366 +0xb8
github.com/dagger/dagger/dagql.NodeFunc[...].func1({0x40018a6700, 0x40007c1c00, {0x0, 0x1, 0x40035eb8c0, 0x4003bd0708}, 0x0}, 0x5f3d5ef38c227790)
        /app/dagql/objects.go:355 +0xf8
github.com/dagger/dagger/dagql.Class[...].Call(0x1d0fb40?, {0x1ce58f8?, 0x40076179b0?}, {0x40018a6700?, 0x40007c1c00, {0x0, 0x1, 0x40035eb8c0, 0x4003bd0708}, 0x0}, ...)
        /app/dagql/objects.go:202 +0x114
github.com/dagger/dagger/dagql.Instance[...].Select(0x1d00340, {0x1ce58f8, 0x40076179b0}, {{0x4003339f6b, 0x8}, {0x2ba64c0, 0x0, 0x0}, 0x0})
        /app/dagql/objects.go:271 +0x24c
github.com/dagger/dagger/dagql.(*Server).cachedSelect.func1({0x1ce58f8?, 0x40076179b0?})
        /app/dagql/server.go:583 +0x54
github.com/dagger/dagger/tracing.AroundFunc.ProgrockAroundFunc.func1({0x1ce58f8, 0x4007617890})
        /app/tracing/graphql.go:102 +0x438
github.com/dagger/dagger/tracing.AroundFunc.SpanAroundFunc.func2({0x1ce58f8, 0x40076171d0})
        /app/tracing/graphql.go:33 +0xa0
github.com/dagger/dagger/dagql.(*cacheMap[...]).GetOrInitializeOnHit(0x1d0bba0, {0x1ce58f8, 0x4007617110}, {0x4001016eb0, 0x47}, 0x40076f4828, 0x4007d37ae8)
        /app/dagql/cachemap.go:85 +0x2c0
github.com/dagger/dagger/dagql.(*cacheMap[...]).GetOrInitialize(0xbd514c?, {0x1ce58f8?, 0x4007617110?}, {0x4001016eb0?, 0xbeb880?}, 0x4007617170?)
        /app/dagql/cachemap.go:60 +0x44
github.com/dagger/dagger/dagql.(*Server).cachedSelect(0x400544f0e0, {0x1ce58f8, 0x4003f49980}, {0x1ce8b60, 0x40037a4940}, {{0x4003339f6b, 0x8}, {0x2ba64c0, 0x0, 0x0}, ...})
        /app/dagql/server.go:592 +0x1b4
github.com/dagger/dagger/dagql.(*Server).resolvePath(0x14ede80?, {0x1ce58f8, 0x4003f49980}, {0x1ce8b60?, 0x40037a4940?}, {{0x4003339f6b, 0x8}, {{0x4003339f6b, 0x8}, {0x2ba64c0, ...}, ...}, ...})
        /app/dagql/server.go:651 +0xf8
github.com/dagger/dagger/dagql.(*Server).Resolve.func1()
        /app/dagql/server.go:405 +0x70
github.com/dagger/dagger/dagql.(*Server).Resolve.(*ErrorPool).Go.func3()
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/pool/error_pool.go:30 +0x2c
github.com/sourcegraph/conc/pool.(*Pool).worker(0x1cc2ca0?)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/pool/pool.go:154 +0x68
github.com/sourcegraph/conc/panics.(*Catcher).Try(0x0?, 0x826e4?)
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/panics/panics.go:23 +0x50
github.com/sourcegraph/conc.(*WaitGroup).Go.func1()
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/waitgroup.go:32 +0x58
created by github.com/sourcegraph/conc.(*WaitGroup).Go in goroutine 661989
        /go/pkg/mod/github.com/sourcegraph/conc@v0.3.0/waitgroup.go:30 +0x7c
```

### Dagger version

dagger v0.10.1 (registry.dagger.io/engine) darwin/arm64

**Comment by KGB33** [comment]
I ran into the same issue, it seems to be fixed on `main` thanks to PR #6838 . 

As a work around the default terminal command can be set manually using `with-default-terminal-cmd`: 

```bash
dagger call -m github.com/shykes/daggerverse/wolfi@v0.1.2 container --packages=cowsay \
      with-default-terminal-cmd --args='sh' \
      terminal
```
