### ISSUE TITLE
🐞 panic: concurrent map read and map write

### ISSUE THREAD

**Issue by sagikazarmark** [dagger/dagger#6937]
### What is the issue?

Pipeline fails with the above error.

Trace:

```
goroutine 1 [running]:
github.com/vito/progrock/console.(*textMux).print(0xc000115e60, 0xc0000ba000)
	/go/pkg/mod/github.com/vito/progrock@v0.10.2-0.20240221152222-63c8df30db8d/console/printer.go:229 +0x185
github.com/vito/progrock/console.(*Writer).Close(0x410565?)
	/go/pkg/mod/github.com/vito/progrock@v0.10.2-0.20240221152222-63c8df30db8d/console/writer.go:87 +0x25
github.com/dagger/dagger/telemetry.LegacyIDInternalizer.Close(...)
	/app/telemetry/legacy.go:40
github.com/dagger/dagger/dagql/idtui.(*Frontend).Close(0x6602dbe7?)
	/app/dagql/idtui/frontend.go:472 +0x38
github.com/vito/progrock.MultiWriter.Close({0xc000378680, 0x1, 0x0?})
	/go/pkg/mod/github.com/vito/progrock@v0.10.2-0.20240221152222-63c8df30db8d/multi.go:19 +0x90
github.com/vito/progrock.(*Recorder).Close(...)
	/go/pkg/mod/github.com/vito/progrock@v0.10.2-0.20240221152222-63c8df30db8d/recorder.go:323
github.com/dagger/dagger/engine/client.(*Client).Close(0xc0001031e0)
	/app/engine/client/client.go:420 +0x3fa
main.runWithFrontend.func1({0x15547c8?, 0xc0004b4cc0?})
	/app/cmd/dagger/engine.go:134 +0x117
github.com/dagger/dagger/dagql/idtui.(*Frontend).runWithoutTUI(0xc000115c20?, {0x15547c8?, 0xc0004b4cc0?}, 0xc00059fa80?, 0xc0001a7d88?)
	/app/dagql/idtui/frontend.go:219 +0x1a9
github.com/dagger/dagger/dagql/idtui.(*Frontend).Run(0xc000115c20, {0x15547c8, 0xc0004b4cc0}, 0x4fa0ac?)
	/app/dagql/idtui/frontend.go:121 +0x65
main.runWithFrontend({0x15547c8, 0xc0004b4cc0}, {{0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0}, {0xc000321080, ...}, ...}, ...)
	/app/cmd/dagger/engine.go:128 +0x205
main.withEngineAndTUI({0x15547c8, 0xc0004b4cc0}, {{0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0}, {0xc000321080, ...}, ...}, ...)
	/app/cmd/dagger/engine.go:88 +0x1b8
main.(*FuncCommand).Command.func2(0xc0004ac600, {0xc00005b110, 0x1, 0x1})
	/app/cmd/dagger/functions.go:257 +0x12b
github.com/spf13/cobra.(*Command).execute(0xc0004ac600, {0xc00005b110, 0x1, 0x1})
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0x1ee38c0)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
	/app/cmd/dagger/main.go:145 +0x2c

goroutine 36 [select]:
github.com/dagger/dagger/analytics.(*CloudTracker).start(0xc0004a4070)
	/app/analytics/analytics.go:184 +0xac
created by github.com/dagger/dagger/analytics.New in goroutine 1
	/app/analytics/analytics.go:140 +0x218

goroutine 80 [runnable]:
github.com/vito/progrock/console.(*textMux).print(0xc000115e60, 0xc0000ba000)
	/go/pkg/mod/github.com/vito/progrock@v0.10.2-0.20240221152222-63c8df30db8d/console/printer.go:234 +0x1ba
github.com/vito/progrock/console.(*Writer).WriteStatus(0xc000115d40, 0xc002ecc200)
	/go/pkg/mod/github.com/vito/progrock@v0.10.2-0.20240221152222-63c8df30db8d/console/writer.go:80 +0xc5
github.com/dagger/dagger/telemetry.LegacyIDInternalizer.WriteStatus({{0x154b138?, 0xc000115d40?}}, 0xc002ecc100)
	/app/telemetry/legacy.go:36 +0x207
github.com/dagger/dagger/dagql/idtui.(*Frontend).WriteStatus(0xc000115c20, 0xc002ecc100)
	/app/dagql/idtui/frontend.go:353 +0xfd
github.com/vito/progrock.MultiWriter.WriteStatus(...)
	/go/pkg/mod/github.com/vito/progrock@v0.10.2-0.20240221152222-63c8df30db8d/multi.go:9
github.com/vito/progrock.(*RPCReceiver).WriteUpdates(0xc00002d128, {0x155a690, 0xc000516250})
	/go/pkg/mod/github.com/vito/progrock@v0.10.2-0.20240221152222-63c8df30db8d/rpc.go:97 +0x53
github.com/vito/progrock._ProgressService_WriteUpdates_Handler({0x11aed00?, 0xc00002d128}, {0x1557d70?, 0xc0000021e0})
	/go/pkg/mod/github.com/vito/progrock@v0.10.2-0.20240221152222-63c8df30db8d/progress_grpc.pb.go:104 +0x91
github.com/moby/buildkit/util/grpcerrors.StreamServerInterceptor({0x11aed00, 0xc00002d128}, {0x1557d70?, 0xc0000021e0?}, 0x10dba00?, 0x13ff700)
	/go/pkg/mod/github.com/moby/buildkit@v0.13.0-beta3/util/grpcerrors/intercept.go:33 +0x71
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000422000, {0x15547c8, 0xc000113620}, {0x155b8a0, 0xc00057e1a0}, 0xc0004f8900, 0xc00022cc30, 0x1ed2c60, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.61.0/server.go:1686 +0x1267
google.golang.org/grpc.(*Server).handleStream(0xc000422000, {0x155b8a0, 0xc00057e1a0}, 0xc0004f8900)
	/go/pkg/mod/google.golang.org/grpc@v1.61.0/server.go:1800 +0xf9b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	/go/pkg/mod/google.golang.org/grpc@v1.61.0/server.go:1029 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 77
	/go/pkg/mod/google.golang.org/grpc@v1.61.0/server.go:1040 +0x135
```

This has been reported before.

Reference: vito/progrock#12

https://github.com/sagikazarmark/daggerverse/actions/runs/8437666663/job/23107986357?pr=62

### Dagger version

dagger v0.10.3 (registry.dagger.io/engine) darwin/arm64

**Comment by helderco** [comment]
Progrock as been replaced with OpenTelemetry in [v0.11.0](https://github.com/dagger/dagger/releases/tag/v0.11.0).
