### ISSUE TITLE
🐞 `github.com/dagger/dagger/dagql/idtui.CollectSpan` invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gerhard** [dagger/dagger#7192]
### What is the issue?

We've hit this error a few times in https://github.com/dagger/dagger/actions/runs/8821414426/job/24217223788?pr=7082, part of:
- https://github.com/dagger/dagger/pull/7082

```
2024-04-24T18:36:16.3979153Z [95m117: [0mDONE 1325 tests, 3 skipped, 2 failures in 605.184s
2024-04-24T18:36:16.3979462Z 
2024-04-24T18:36:16.3979728Z panic: runtime error: invalid memory address or nil pointer dereference
2024-04-24T18:36:16.3980302Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x4b pc=0xf4363d]
2024-04-24T18:36:16.3980649Z 
2024-04-24T18:36:16.3980743Z goroutine 1 [running]:
2024-04-24T18:36:16.3981331Z github.com/dagger/dagger/dagql/idtui.CollectSpans(0xc0003e0120, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
2024-04-24T18:36:16.3981982Z 	/app/dagql/idtui/types.go:52 +0x41d
2024-04-24T18:36:16.3982474Z github.com/dagger/dagger/dagql/idtui.(*Frontend).recalculateView(0xc0003e20d0)
2024-04-24T18:36:16.3983016Z 	/app/dagql/idtui/frontend.go:395 +0x33
2024-04-24T18:36:16.3983493Z github.com/dagger/dagger/dagql/idtui.(*Frontend).finalRender(0xc0003e20d0)
2024-04-24T18:36:16.3983984Z 	/app/dagql/idtui/frontend.go:217 +0xa5
2024-04-24T18:36:16.3984563Z github.com/dagger/dagger/dagql/idtui.(*Frontend).Run(0xc0003e20d0, {0x1419d10, 0x1d6d6c0}, 0x12e4450)
2024-04-24T18:36:16.3985182Z 	/app/dagql/idtui/frontend.go:131 +0xe5
2024-04-24T18:36:16.3985471Z main.main()
2024-04-24T18:36:16.3985706Z 	/app/cmd/dagger/main.go:212 +0xac
2024-04-24T18:36:16.4731230Z Error: exit status 2
2024-04-24T18:36:16.4748865Z exit status 1
```

Just in case those logs become unavailable, I am attaching them as `zip`: [logs_23113975550.zip](https://github.com/dagger/dagger/files/15109954/logs_23113975550.zip)

cc @vito 

### Dagger version

dagger v0.11.1 (registry.dagger.io/engine) linux/amd64

**Comment by jedevc** [comment]
x-linking to https://github.com/dagger/dagger/pull/7227 - this should at least stop the panic.

**Comment by gerhard** [comment]
Just hit this on `v0.11.2` here https://github.com/dagger/dagger/actions/runs/8986651161/job/24683291279#step:4:68

```console
dagger call lint stdout
...

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4b pc=0xf436bd]

goroutine 1 [running]:
github.com/dagger/dagger/dagql/idtui.CollectSpans(0xc0004660c0, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
	/app/dagql/idtui/types.go:52 +0x41d
github.com/dagger/dagger/dagql/idtui.(*Frontend).recalculateView(0xc000468000)
	/app/dagql/idtui/frontend.go:[39](https://github.com/dagger/dagger/actions/runs/8986651161/job/24683291279#step:4:40)5 +0x33
github.com/dagger/dagger/dagql/idtui.(*Frontend).finalRender(0xc000468000)
	/app/dagql/idtui/frontend.go:217 +0xa5
github.com/dagger/dagger/dagql/idtui.(*Frontend).Run(0xc000468000, {0x1[41](https://github.com/dagger/dagger/actions/runs/8986651161/job/24683291279#step:4:42)98b0, 0x1d6d680}, 0x12e3fd8)
	/app/dagql/idtui/frontend.go:131 +0xe5
main.main()
	/app/cmd/dagger/main.go:225 +0xac
Error: exit status 2
exit status 1
```

Looking forward to trying out https://github.com/dagger/dagger/pull/7227 when `v0.11.3` becomes available.

cc @matipan

**Comment by gerhard** [comment]
Haven't see this in a while, closing since it must have been addressed. FTR:
- #7452 
- #7605 
- #7996
