### ISSUE TITLE
🐞 unhandled errors in a TaskGroup

### ISSUE THREAD

**Issue by michaeljohnalbers** [dagger/dagger#7509]
### What is the issue?

When using the Python SDK, many errors during development of functions are surfaced as
```
╭─ Error ──────────────────────────────────────────────────────────────────────╮
│ Failed to unstructure result: unknown error (unhandled errors in a TaskGroup │
│ (1 sub-exception)) @ main.Common.build                                       │
╰──────────────────────────────────────────────────────────────────────────────╯
```
Turning on debugging doesn't provide anything more useful as the underlying error is just
```
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/src/dagger/sdk/src/dagger/client/_core.py", line 199, in _resolve_id
    |     sel.args[k] = await v.id()
    |                   ^^^^^^^^^^^^
    |   File "<@beartype(dagger.client.gen.Directory.id) at 0x7905eb70ec00>", line 11, in id
    |   File "/src/dagger/sdk/src/dagger/client/gen.py", line 2067, in id
    |     _ctx = self._select("id", _args)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/src/dagger/sdk/src/dagger/client/base.py", line 51, in _select
    |     return self._ctx.select(self._graphql_name(), *args, **kwargs)
    |            ^^^^^^^^^^^^^^^^
    | AttributeError: 'str' object has no attribute 'select'
    +------------------------------------

The above exception was the direct cause of the following exception:
```

### Dagger version

dagger v0.11.5 (registry.dagger.io/engine) linux/amd64

### Steps to reproduce

1. Create a new module, `dagger init --sdk=python common`
2. Replace the contents of **__init__.py** with this
```python
import dagger
from dagger import dag, function, object_type
from .git import *

@object_type
class Common:
    @function
    def dummy(self, project: str) -> dagger.Directory:
        return clone(project, dagger.Directory("/app"))

```
3. Create a source file named **git.py** with the following contents
```python
import dagger
from dagger import dag

def clone(project: str, destination: dagger.Directory) -> dagger.Directory:
    workdir = "/repo"
    certs = dagger.Directory("/etc/ssl/certs")
    return (dag.container()
     .with_mounted_directory("/etc/ssl/certs", certs)
     .with_directory(workdir, destination)
     .directory("/")
     )
```
4. Run dagger: `dagger call -m ./common/ dummy --project="hi"`. You should see the following error
```
Error: response from query: input: common.dummy resolve: call function "dummy": process "/runtime" did not complete successfully: exit code: 1

Stderr:
╭─ Error ──────────────────────────────────────────────────────────────────────╮
│ Failed to unstructure result: unknown error (unhandled errors in a TaskGroup │
│ (2 sub-exceptions)) @ main.Common.dummy                                      │
╰──────────────────────────────────────────────────────────────────────────────╯
```
The two sub-exceptions corresponds to the `with_mounted_directory` and `with_directory` calls.

**Comment by michaeljohnalbers** [comment]
If I use `dagger.directory` I get an error saying it doesn't exist. If I try `dag.directory` it's listed as deprecated.

**Comment by skycaptain** [comment]
Sorry, I meant `Client.directory`. Reading the [[Python API docs](https://dagger-io.readthedocs.io/)](https://dagger-io.readthedocs.io/) may help you understand how to use the function correctly. The deprecation notice likely results from passing a path as an ID. From your example, I couldn't discern your intended action. Could you please provide more details?

**Comment by helderco** [comment]
That's right. Objects can't be instantiated directly, they need the go through dagger.Client of which `dag` is an instance of. Meaning that `dagger.Query.directory() -> Directory` is called with `src = dag.directory()`. This creates an empty directory. The path is only needed when you add or mount a directory to either another directory or a container.

**Comment by michaeljohnalbers** [comment]
@skycaptain I'm trying to mount a few directories from the user's machine into the container running some stuff (Maven build & git operations).
