### ISSUE TITLE
🐞 elixir: runtime crash when move the `deps.get` out of the entrypoint in runtime

### ISSUE THREAD

**Issue by wingyplus** [dagger/dagger#8352]
### What is the issue?

I'm trying to move `deps.get` out of the entrypoint in runtime and got this error:
```
Error: response from query: input: potato.containerEcho resolve: call function "ContainerEcho": process "mix cmd --cd /src/sdk/elixir/potato/potato mix do deps.get --only dev + dagger.invoke" did not complete successfully: exit code: 1

Stdout:
Resolving Hex dependencies...
Resolution completed in 0.035s
Unchanged:
  jason 1.4.4
  nimble_options 1.1.1
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an already existing atom

    :erlang.binary_to_existing_atom("container_echo", :utf8)
    (dagger 0.0.0) lib/dagger/mod.ex:40: Dagger.Mod.invoke/6
    (dagger 0.0.0) lib/dagger/mod.ex:22: Dagger.Mod.invoke/2
    (mix 1.17.2) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (elixir 1.17.2) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
    (mix 1.17.2) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.17.2) lib/mix/cli.ex:96: Mix.CLI.run_task/2
    /usr/local/bin/mix:2: (file)
Stderr:
** (exit) 1
    (mix 1.17.2) lib/mix/tasks/cmd.ex:74: Mix.Tasks.Cmd.run/1
    (mix 1.17.2) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.17.2) lib/mix/cli.ex:96: Mix.CLI.run_task/2
    /usr/local/bin/mix:2: (file)
```

### Dagger version

0.12.7

**Comment by wingyplus** [comment]
Found that it's because of the cache. Prune it can make this error disappear
