### ISSUE TITLE
🐞 Rust SDK fails to export container and throws invalid type error

### ISSUE THREAD

**Issue by jdno** [dagger/dagger#8505]
### What is the issue?

I am trying to build a container with the Rust SDK and export it afterwards. Building the container works fine, but when trying to export it I get an error that seems to point to mismatched types somewhere in the API layer.

```
Unpack(Deserialize(Error("invalid type: boolean `true`, expected a string", line: 0, column: 0)))
```

### Dagger version

dagger v0.13.0 (registry.dagger.io/engine:v0.13.0) darwin/arm64

### Steps to reproduce

First, create a new Rust crate and add the necessary dependencies

```shell
cargo new --bin --vcs none dagger-invalid-type
cd dagger-invalid-type
cargo add dagger-sdk
cargo add tokio -F full
```

Replace the contents of `main.rs` with this minimal reproducible example:

```rust
#[tokio::main]
async fn main() {
    dagger_sdk::connect(|client| async move {
        client
            .container()
            .from("alpine")
            .export("/tmp/dagger-invalid-type.tar")
            .await
            .unwrap();

        Ok(())
    })
    .await
    .unwrap()
}
```

Run the build with `cargo run` or `RUST_BACKTRACE=full cargo run` if you want to print the stacktrace.

### Log output

```
❯ RUST_BACKTRACE=full cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.28s
     Running `target/debug/dagger-invalid-type`
1   : connect
2   :   starting engine
3   :   create
3   :   create DONE [0.9s]
2   :   starting engine DONE [0.9s]
4   :   connecting to engine
4   :   | engine name=30f89b741806 version=v0.11.9 client=qvh87qt6zyjsm4dt312srb13y
4   :   connecting to engine DONE [0.1s]
1   : connect DONE [1.0s]

5   : container: Container!
5   : container DONE [0.0s]

6   : Container.from(address: "alpine"): Container!
thread 'main' panicked at src/main.rs:9:14:
called `Result::unwrap()` on an `Err` value: Unpack(Deserialize(Error("invalid type: boolean `true`, expected a string", line: 0, column: 0)))
stack backtrace:
6   : Container.from DONE [0.4s]

7   : Container.export(path: "/tmp/dagger-invalid-type.tar"): Boolean!
   0:        0x103332368 - std::backtrace_rs::backtrace::libunwind::trace::hbebc8679d47bdc2c
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:        0x103332368 - std::backtrace_rs::backtrace::trace_unsynchronized::h3a2e9637943241aa
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x103332368 - std::sys::backtrace::_print_fmt::he430849680584674
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:65:5
   3:        0x103332368 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h243268f17d714c7f
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:40:26
   4:        0x10334fa68 - core::fmt::rt::Argument::fmt::h0d339881c25f3c31
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/fmt/rt.rs:173:76
   5:        0x10334fa68 - core::fmt::write::hb3cfb8a30e72d7ff
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/fmt/mod.rs:1182:21
   6:        0x10332f3a8 - std::io::Write::write_fmt::hfb2314975de9ecf1
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/io/mod.rs:1827:15
   7:        0x103333444 - std::sys::backtrace::BacktraceLock::print::he14461129ccbfef5
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:43:9
   8:        0x103333444 - std::panicking::default_hook::{{closure}}::h14c7718ccf39d316
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:269:22
   9:        0x103333068 - std::panicking::default_hook::hc62e60da3be2f352
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:296:9
  10:        0x103333f08 - std::panicking::rust_panic_with_hook::h09e8a656f11e82b2
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:800:13
  11:        0x103333858 - std::panicking::begin_panic_handler::{{closure}}::h1230eb3cc91b241c
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:674:13
  12:        0x1033327f4 - std::sys::backtrace::__rust_end_short_backtrace::hc3491307aceda2c2
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:168:18
  13:        0x103333520 - rust_begin_unwind
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
  14:        0x10336705c - core::panicking::panic_fmt::ha4b80a05b9fff47a
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
  15:        0x103367478 - core::result::unwrap_failed::h441932a0bca0dd7f
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/result.rs:1679:5
  16:        0x102cb4b98 - core::result::Result<T,E>::unwrap::hcc10afbd148404e6
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/result.rs:1102:23
  17:        0x102cb4b98 - dagger_invalid_type::main::{{closure}}::{{closure}}::{{closure}}::h3bdc9ce30510fa0b
                               at /Users/jdn/Developer/jdno/dagger-invalid-type/src/main.rs:4:9
  18:        0x102cc2760 - dagger_sdk::client::connect_opts::{{closure}}::h6827043b2c574aa5
                               at /Users/jdn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dagger-sdk-0.11.10/src/client.rs:42:20
  19:        0x102cc2d8c - dagger_sdk::client::connect::{{closure}}::hba3745e26558385a
                               at /Users/jdn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dagger-sdk-0.11.10/src/client.rs:21:31
  20:        0x102cb4770 - dagger_invalid_type::main::{{closure}}::he5897e89ebc861d6
                               at /Users/jdn/Developer/jdno/dagger-invalid-type/src/main.rs:13:6
  21:        0x102cdbde8 - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::h1c68725643ead88e
                               at /Users/jdn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/park.rs:281:63
  22:        0x102cdbc70 - tokio::runtime::coop::with_budget::h87e813637eb9e4be
                               at /Users/jdn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:107:5
  23:        0x102cdbc70 - tokio::runtime::coop::budget::h407377e884594ec8
                               at /Users/jdn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:73:5
  24:        0x102cdbc70 - tokio::runtime::park::CachedParkThread::block_on::he56ac53c708fa7d3
                               at /Users/jdn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/park.rs:281:31
  25:        0x102cbc548 - tokio::runtime::context::blocking::BlockingRegionGuard::block_on::hd54efb22ac94d794
                               at /Users/jdn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/blocking.rs:66:9
  26:        0x102caa090 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}::hccdc2b5b238287e2
                               at /Users/jdn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  27:        0x102cc0d5c - tokio::runtime::context::runtime::enter_runtime::h41b9dce147cf6e70
                               at /Users/jdn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/runtime.rs:65:16
  28:        0x102ca9fe4 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::haaa21fb784946777
                               at /Users/jdn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  29:        0x102cd6690 - tokio::runtime::runtime::Runtime::block_on_inner::h53a08a080c08514f
                               at /Users/jdn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs:363:45
  30:        0x102cd678c - tokio::runtime::runtime::Runtime::block_on::h5e56ad2506ef3588
                               at /Users/jdn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs:335:13
  31:        0x102cb660c - dagger_invalid_type::main::hdf26e4f85e0296fd
                               at /Users/jdn/Developer/jdno/dagger-invalid-type/src/main.rs:3:5
  32:        0x102ca1f88 - core::ops::function::FnOnce::call_once::h3f40c82fa71f1ea0
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
  33:        0x102cc0ad0 - std::sys::backtrace::__rust_begin_short_backtrace::hed3ffd1b1ce21bc9
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:152:18
  34:        0x102cc6a18 - std::rt::lang_start::{{closure}}::h3f6fb06fe5e809ea
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:162:18
  35:        0x10332b2a0 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h4f74490c6170ea16
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:284:13
  36:        0x10332b2a0 - std::panicking::try::do_call::h2f36d2f1f1af8d28
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
  37:        0x10332b2a0 - std::panicking::try::ha6af9029a7d93c94
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
  38:        0x10332b2a0 - std::panic::catch_unwind::ha4f738ae2ba7c3a4
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
  39:        0x10332b2a0 - std::rt::lang_start_internal::{{closure}}::hf216622dc2c733e3
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:141:48
  40:        0x10332b2a0 - std::panicking::try::do_call::haa691957db1dd55f
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
  41:        0x10332b2a0 - std::panicking::try::ha0c1a49b9fabc98e
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
  42:        0x10332b2a0 - std::panic::catch_unwind::h68ad032c646bb0ab
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
  43:        0x10332b2a0 - std::rt::lang_start_internal::hdd117cb81a316264
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:141:20
  44:        0x102cc69e4 - std::rt::lang_start::h9c3e59b312391bff
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:161:17
  45:        0x102cb6694 - _main
```

**Comment by jedevc** [comment]
cc @dagger/sdk-rust

**Comment by wingyplus** [comment]
The [export](https://github.com/dagger/dagger/blob/v0.11.9/core/schema/container.go#L1214) api on 0.11.9 retrurns boolean while the generated api returns a string. It looks like that the sdk forgot to bump the engine version before publishing to crates registry, cause the api broken when use it together with auto provision engine. I believe that the issue is disappear if running it with dagger run.

The issue is disappear on the main branch, the engine version is up-to-date now.

**Comment by jdno** [comment]
I can confirm that the error is fixed when pulling in the crate from the main branch. 👍

Unrelated, but maybe worth noting, is that the crate version on the main branch is still `0.9.8`.

**Comment by wingyplus** [comment]
I see they’ve a discussion about release process in [1] and [2]. That’s why the version in the repo never gets up-to-date.

[1] https://github.com/dagger/dagger/pull/8085
[2] https://discord.com/channels/707636530424053791/1141601893538332704/1270371421335453708
