### ISSUE TITLE
shell: panic on int arguments

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#9032]
In `dagger shell`, calling a function with an argument that is an integer, causes a panic with "unsupported argument of kind float64".

Example:

```console
⋈ .container | with-exposed-port 80
```

In v0.14.0 this results in the following output:

```console
panic: unsupported argument of kind float64

goroutine 109 [running]:
dagger.io/dagger/querybuilder.marshalValue({0x103379df0, 0x14001139400}, {0x1030d8220?, 0x140009224b0?, 0x2?})
                                                                     	/app/sdk/go/querybuilder/marshal.go:132 +0x5b0
                                                                                                                      dagger.io/dagger/querybuilder.MarshalGQL({0x103379df0?, 0x14001139400?}, {0x1030d8220?, 0x140009224b0?})
                                                                               	/app/sdk/go/querybuilder/marshal.go:43 +0x88
                                                                                                                            dagger.io/dagger/querybuilder.(*argument).marshal.func1()
                                      	/app/sdk/go/querybuilder/querybuilder.go:210 +0x34
                                                                                          sync.(*Once).doSlow(0x0?, 0x0?)
                                                                                                                         	/usr/local/go/src/sync/once.go:76 +0xf8
                        sync.(*Once).Do(...)
                                            	/usr/local/go/src/sync/once.go:67
                                                                                 dagger.io/dagger/querybuilder.(*argument).marshal(0x14000d8c200, {0x103379df0?, 0x14001139400?})
                                  	/app/sdk/go/querybuilder/querybuilder.go:209 +0x5c
                                                                                          dagger.io/dagger/querybuilder.(*Selection).marshalArguments.func1()
              	/app/sdk/go/querybuilder/querybuilder.go:90 +0x28
                                                                 golang.org/x/sync/errgroup.(*Group).Go.func1()
                                                                                                               	/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 +0x54
                                   created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 51
                                                                                                    	/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:75 +0x98
```

**Comment by helderco** [comment]
This happens because we marshal arguments and unmarshal back, between pipes. However, when you unmarshal an integer from JSON into an `interface{}`, it becomes a `float64`: https://pkg.go.dev/encoding/json#Unmarshal.

Quick fix is to use the introspection to find all integers and cast back to int before building the query. At some point I'd like to explore encoding/decoding without going through JSON.
