### ISSUE TITLE
🐞 Basic pypi example doesn't work

### ISSUE THREAD

**Issue by peekxc** [dagger/dagger#9092]
### What is the issue?

> (default) mpiekenbrock{~/primate} python main.py "hello"

FYI the basic dagger program shown on the [PyPI page](https://pypi.org/project/dagger-io/) doesn't work as expected. 

### Dagger version

dagger v0.14.0 (registry.dagger.io/engine:v0.14.0) darwin/amd64

### Steps to reproduce

1. `brew install dagger/tap/dagger`
2. `pip install dagger-io`
3. Copy + paste `main.py` example somewhere
4. Observe `python -m main.py` yields many errors 

### Log output

Traceback (most recent call last):
  File
"/Users/mpiekenbrock/opt/miniconda3/envs/default/lib/python3.11/site-packages/dagger/client/_core.py",
line 137, in execute
    result = await self.conn.session.execute(query)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"/Users/mpiekenbrock/opt/miniconda3/envs/default/lib/python3.11/site-packages/dagger/client/_session.py"
, line 139, in execute
    return await (await self.get_session()).execute(query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpiekenbrock/opt/miniconda3/envs/default/lib/python3.11/site-packages/gql/client.py",
line 1639, in execute
    raise TransportQueryError(
gql.transport.exceptions.TransportQueryError: {'message': 'resolve: process "hello" did not complete
successfully: exit code: 2', 'path': ['container', 'from', 'withExec', 'withEntrypoint', 'withExec',
'stdout'], 'extensions': {'_type': 'EXEC_ERROR', 'cmd': ['hello'], 'exitCode': 2, 'stderr': '[dumb-init]
hello: No such file or directory', 'stdout': ''}}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mpiekenbrock/primate/main.py", line 19, in <module>
    anyio.run(main, sys.argv[1:])
  File
"/Users/mpiekenbrock/opt/miniconda3/envs/default/lib/python3.11/site-packages/anyio/_core/_eventloop.py"
, line 74, in run
    return async_backend.run(func, args, {}, backend_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"/Users/mpiekenbrock/opt/miniconda3/envs/default/lib/python3.11/site-packages/anyio/_backends/_asyncio.p
y", line 2207, in run
    return runner.run(wrapper())
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpiekenbrock/opt/miniconda3/envs/default/lib/python3.11/asyncio/runners.py", line 118, in
run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mpiekenbrock/opt/miniconda3/envs/default/lib/python3.11/asyncio/base_events.py", line
654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File
"/Users/mpiekenbrock/opt/miniconda3/envs/default/lib/python3.11/site-packages/anyio/_backends/_asyncio.p
y", line 2195, in wrapper
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/Users/mpiekenbrock/primate/main.py", line 14, in main
    result = await ctr.with_exec(args).stdout()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(dagger.client.gen.Container.stdout) at 0x10814b060>", line 11, in stdout
  File
"/Users/mpiekenbrock/opt/miniconda3/envs/default/lib/python3.11/site-packages/dagger/client/gen.py",
line 1015, in stdout
    return await _ctx.execute(str)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File
"/Users/mpiekenbrock/opt/miniconda3/envs/default/lib/python3.11/site-packages/dagger/client/_core.py",
line 162, in execute
    raise error from e
dagger.ExecError: resolve: process "hello" did not complete successfully: exit code: 2
Stdout:

Stderr:
[dumb-init] hello: No such file or directory
⠇ Disconnecting%

**Comment by samalba** [comment]
The instructions from PyPI page aren't correct anymore, we should update them to match what's in the official docs: [https://docs.dagger.io/quickstart/daggerize](https://docs.dagger.io/quickstart/daggerize)<br><br>cc @helder

**Comment by helderco** [comment]
Yeah that example uses an entrypoint and those aren't used by default anymore. :
```diff
     async with dagger.connection():
         # build container with cowsay entrypoint
         ctr = (
             dag.container()
             .from_("python:alpine")
             .with_exec(["pip", "install", "cowsay"])
-            .with_entrypoint(["cowsay"])
         )

         # run cowsay with requested message
-        result = await ctr.with_exec(args).stdout()
+        result = await ctr.with_exec(["cowsay", *args]).stdout()
```
```console
$ uv run --with dagger-io --isolated main.py -t "Simple is better than complex"
  _____________________________
| Simple is better than complex |
  =============================
                             \
                              \
                                ^__^
                                (oo)\_______
                                (__)\       )\/\
                                    ||----w |
                                    ||     ||

```

**Comment by helderco** [comment]
> The instructions from PyPI page aren't correct anymore, we should update them to match what's in the official docs: https://docs.dagger.io/quickstart/daggerize

I think the example that shows in PyPI should continue to be a `dagger run` use case because the library that's published is not for Dagger modules. No problem in pointing to that direction though.
